export interface DojoPostgresMigration {
  id: string;
  description: string;
  statements: string[];
}

export const DOJO_POSTGRES_REQUIRED_TABLES = [
  "dojo_tenants",
  "dojo_workspaces",
  "dojo_skills",
  "dojo_skill_versions",
  "dojo_skill_graphs",
  "dojo_node_memories",
  "dojo_graph_execution_runs",
  "dojo_licenses",
  "dojo_license_versions",
  "dojo_proof_records",
  "dojo_proof_keys",
  "dojo_app_releases",
  "dojo_source_snapshots",
  "dojo_source_tokens",
  "dojo_evidence_records",
  "dojo_therapeutic_runtime_states",
  "dojo_ledger_checkpoints",
  "dojo_checkride_runs",
  "dojo_scenario_runs",
  "dojo_case_law",
  "dojo_antibodies",
  "dojo_approvals",
  "dojo_ghost_shadow_evidence",
  "dojo_tool_registrations",
  "dojo_tool_invocations",
  "dojo_mcp_host_conformance_results",
  "dojo_runtime_sessions",
  "dojo_audit_events",
] as const;

export type DojoPostgresRequiredTable = (typeof DOJO_POSTGRES_REQUIRED_TABLES)[number];

export const DOJO_POSTGRES_MIGRATIONS: DojoPostgresMigration[] = [
  {
    id: "001_dojo_control_plane_foundation",
    description: "Create tenant-scoped Dojo control-plane tables for skills, licenses, proof records, and audit events.",
    statements: [
      `CREATE TABLE IF NOT EXISTS dojo_tenants (
        tenant_id TEXT PRIMARY KEY,
        organization_id TEXT,
        display_name TEXT NOT NULL,
        data_region TEXT,
        encryption_key_ref TEXT,
        retention_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_workspaces (
        tenant_id TEXT NOT NULL REFERENCES dojo_tenants(tenant_id) ON DELETE RESTRICT,
        workspace_id TEXT NOT NULL,
        organization_id TEXT,
        app_origin TEXT,
        data_region TEXT,
        policy_set JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, workspace_id)
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_skills (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        workflow_id TEXT NOT NULL,
        name TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'draft',
        current_skill_version TEXT,
        skill_json JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, skill_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        UNIQUE (tenant_id, workspace_id, workflow_id)
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_skill_versions (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        skill_version TEXT NOT NULL,
        graph_version TEXT,
        seed_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        graph_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_by TEXT,
        PRIMARY KEY (tenant_id, skill_id, skill_version),
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE CASCADE,
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_licenses (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        license_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        license_version TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        entrustment_level TEXT NOT NULL,
        readiness_level INTEGER NOT NULL,
        license_json JSONB NOT NULL,
        expires_at TIMESTAMPTZ,
        revoked_at TIMESTAMPTZ,
        revoked_reason TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, license_id),
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        UNIQUE (tenant_id, skill_id, license_version),
        CHECK (status IN ('active', 'expired', 'revoked', 'superseded'))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_proof_records (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        capsule_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        license_id TEXT,
        requested_action TEXT NOT NULL,
        nonce TEXT,
        status TEXT NOT NULL,
        issued_at TIMESTAMPTZ NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL,
        first_used_at TIMESTAMPTZ,
        last_validated_at TIMESTAMPTZ,
        revoked_at TIMESTAMPTZ,
        revoked_reason TEXT,
        proof_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, capsule_id),
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, license_id) REFERENCES dojo_licenses(tenant_id, license_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        UNIQUE (tenant_id, nonce),
        CHECK (status IN ('issued', 'used', 'revoked'))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_audit_events (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        audit_event_id TEXT NOT NULL,
        actor_id TEXT NOT NULL,
        actor_type TEXT NOT NULL,
        event_type TEXT NOT NULL,
        request_id TEXT NOT NULL,
        correlation_id TEXT NOT NULL,
        entity_kind TEXT,
        entity_id TEXT,
        details JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, audit_event_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        CHECK (actor_type IN ('human', 'agent', 'service'))
      )`,
      "CREATE INDEX IF NOT EXISTS dojo_workspaces_tenant_idx ON dojo_workspaces (tenant_id, workspace_id)",
      "CREATE INDEX IF NOT EXISTS dojo_skills_workflow_idx ON dojo_skills (tenant_id, workspace_id, workflow_id)",
      "CREATE INDEX IF NOT EXISTS dojo_skills_status_idx ON dojo_skills (tenant_id, workspace_id, status)",
      "CREATE INDEX IF NOT EXISTS dojo_skill_versions_created_idx ON dojo_skill_versions (tenant_id, skill_id, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_licenses_skill_idx ON dojo_licenses (tenant_id, skill_id, status)",
      "CREATE INDEX IF NOT EXISTS dojo_proof_records_status_idx ON dojo_proof_records (tenant_id, workspace_id, status)",
      "CREATE INDEX IF NOT EXISTS dojo_proof_records_skill_idx ON dojo_proof_records (tenant_id, skill_id, requested_action)",
      "CREATE INDEX IF NOT EXISTS dojo_audit_events_created_idx ON dojo_audit_events (tenant_id, workspace_id, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_audit_events_correlation_idx ON dojo_audit_events (tenant_id, correlation_id)",
    ],
  },
  {
    id: "002_dojo_evidence_ledger",
    description: "Create append-only evidence ledger records and ledger checkpoints.",
    statements: [
      `CREATE TABLE IF NOT EXISTS dojo_evidence_records (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        append_sequence BIGSERIAL,
        record_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        run_id TEXT NOT NULL,
        kind TEXT NOT NULL,
        artifact_uri TEXT NOT NULL,
        artifact_sha256 TEXT NOT NULL,
        redaction_manifest_sha256 TEXT,
        claim_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        previous_hash TEXT NOT NULL,
        record_hash TEXT NOT NULL,
        ledger_head_hash TEXT NOT NULL,
        signer_key_id TEXT,
        signature TEXT,
        created_at TIMESTAMPTZ NOT NULL,
        created_by TEXT NOT NULL,
        retention_class TEXT NOT NULL,
        legal_hold BOOLEAN NOT NULL DEFAULT false,
        source_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        record_json JSONB NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, record_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        UNIQUE (tenant_id, workspace_id, record_hash),
        CHECK (artifact_sha256 ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (previous_hash ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (record_hash ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (ledger_head_hash ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (redaction_manifest_sha256 IS NULL OR redaction_manifest_sha256 ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (retention_class IN ('ephemeral', 'standard', 'regulated', 'legal_hold'))
      )`,
      "ALTER TABLE dojo_evidence_records ADD COLUMN IF NOT EXISTS append_sequence BIGSERIAL",
      `CREATE TABLE IF NOT EXISTS dojo_ledger_checkpoints (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        checkpoint_id TEXT NOT NULL,
        ledger_head_hash TEXT NOT NULL,
        record_count INTEGER NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, checkpoint_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        CHECK (ledger_head_hash ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (record_count >= 0)
      )`,
      "CREATE INDEX IF NOT EXISTS dojo_evidence_records_run_idx ON dojo_evidence_records (tenant_id, workspace_id, run_id)",
      "CREATE INDEX IF NOT EXISTS dojo_evidence_records_skill_idx ON dojo_evidence_records (tenant_id, workspace_id, skill_id, created_at ASC)",
      "CREATE INDEX IF NOT EXISTS dojo_evidence_records_append_sequence_idx ON dojo_evidence_records (tenant_id, workspace_id, append_sequence ASC)",
      "CREATE INDEX IF NOT EXISTS dojo_evidence_records_claim_idx ON dojo_evidence_records USING GIN (claim_ids)",
      "CREATE INDEX IF NOT EXISTS dojo_ledger_checkpoints_head_idx ON dojo_ledger_checkpoints (tenant_id, workspace_id, record_count DESC, created_at DESC)",
    ],
  },
  {
    id: "003_dojo_hosted_runtime_sessions",
    description: "Create tenant-scoped hosted runtime session records for Dojo skill runs.",
    statements: [
      `CREATE TABLE IF NOT EXISTS dojo_runtime_sessions (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        session_id TEXT NOT NULL,
        runtime_id TEXT NOT NULL,
        organization_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        run_id TEXT NOT NULL,
        actor_id TEXT NOT NULL,
        actor_type TEXT NOT NULL,
        workspace_url TEXT NOT NULL,
        workspace_origin TEXT NOT NULL,
        origin_allowlist TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        status TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL,
        revoked_at TIMESTAMPTZ,
        revoked_reason TEXT,
        credential_id TEXT NOT NULL,
        credential_sha256 TEXT NOT NULL,
        credential_expires_at TIMESTAMPTZ NOT NULL,
        local_network_allowed BOOLEAN NOT NULL DEFAULT false,
        redact_screenshots BOOLEAN NOT NULL DEFAULT true,
        audit_event_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        evidence_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        session_json JSONB NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, workspace_id, session_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        CHECK (actor_type IN ('human', 'agent', 'service')),
        CHECK (status IN ('active', 'revoked', 'expired')),
        CHECK (credential_sha256 ~ '^[A-Fa-f0-9]{64}$')
      )`,
      "CREATE INDEX IF NOT EXISTS dojo_runtime_sessions_skill_idx ON dojo_runtime_sessions (tenant_id, workspace_id, skill_id, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_runtime_sessions_run_idx ON dojo_runtime_sessions (tenant_id, workspace_id, run_id, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_runtime_sessions_status_idx ON dojo_runtime_sessions (tenant_id, workspace_id, status, expires_at ASC)",
    ],
  },
  {
    id: "004_dojo_maturity_control_plane_registries",
    description: "Create mature Dojo registry tables for graph versions, source snapshots, scenario runs, governance, and MCP skill bus state.",
    statements: [
      `CREATE TABLE IF NOT EXISTS dojo_app_releases (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        app_release_id TEXT NOT NULL,
        app_origin TEXT NOT NULL,
        app_version TEXT NOT NULL,
        commit_sha TEXT,
        source_map_sha256 TEXT,
        framework_adapter TEXT,
        status TEXT NOT NULL DEFAULT 'active',
        release_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_by TEXT,
        PRIMARY KEY (tenant_id, workspace_id, app_release_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        UNIQUE (tenant_id, workspace_id, app_origin, app_version),
        CHECK (source_map_sha256 IS NULL OR source_map_sha256 ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (status IN ('active', 'superseded', 'revoked'))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_source_snapshots (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        snapshot_id TEXT NOT NULL,
        app_release_id TEXT NOT NULL,
        app_origin TEXT NOT NULL,
        app_version TEXT NOT NULL,
        commit_sha TEXT NOT NULL,
        source_map_sha256 TEXT,
        snapshot_sha256 TEXT NOT NULL,
        signer_key_id TEXT NOT NULL,
        signature TEXT NOT NULL,
        snapshot_json JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_by TEXT NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, snapshot_id),
        FOREIGN KEY (tenant_id, workspace_id, app_release_id) REFERENCES dojo_app_releases(tenant_id, workspace_id, app_release_id) ON DELETE RESTRICT,
        CHECK (source_map_sha256 IS NULL OR source_map_sha256 ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (snapshot_sha256 ~ '^[A-Fa-f0-9]{64}$')
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_source_tokens (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        snapshot_id TEXT NOT NULL,
        token_id TEXT NOT NULL,
        component_path TEXT NOT NULL,
        route TEXT,
        stable_action_name TEXT,
        source_locator TEXT NOT NULL,
        risk TEXT NOT NULL,
        proof_required BOOLEAN NOT NULL DEFAULT false,
        allowed_substrate TEXT NOT NULL,
        compatibility_status TEXT NOT NULL DEFAULT 'current',
        token_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, workspace_id, snapshot_id, token_id),
        FOREIGN KEY (tenant_id, workspace_id, snapshot_id) REFERENCES dojo_source_snapshots(tenant_id, workspace_id, snapshot_id) ON DELETE CASCADE,
        CHECK (risk IN ('safe', 'low', 'medium', 'high', 'critical')),
        CHECK (allowed_substrate IN ('vision', 'dom', 'source', 'api', 'mcp')),
        CHECK (compatibility_status IN ('current', 'drifted', 'deprecated', 'blocked'))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_skill_graphs (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        graph_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        skill_version TEXT NOT NULL,
        graph_version TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'draft',
        graph_sha256 TEXT NOT NULL,
        graph_json JSONB NOT NULL,
        validation_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_by TEXT,
        PRIMARY KEY (tenant_id, workspace_id, graph_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, skill_id, skill_version) REFERENCES dojo_skill_versions(tenant_id, skill_id, skill_version) ON DELETE CASCADE,
        CHECK (graph_sha256 ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (status IN ('draft', 'checkride', 'licensed', 'expired', 'revoked'))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_node_memories (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        graph_id TEXT NOT NULL,
        node_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        node_kind TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        confidence DOUBLE PRECISION,
        evidence_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        memory_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, workspace_id, graph_id, node_id),
        FOREIGN KEY (tenant_id, workspace_id, graph_id) REFERENCES dojo_skill_graphs(tenant_id, workspace_id, graph_id) ON DELETE CASCADE,
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE CASCADE,
        CHECK (status IN ('active', 'disabled', 'expired', 'needs_review')),
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_graph_execution_runs (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        graph_run_id TEXT NOT NULL,
        graph_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        mode TEXT NOT NULL,
        status TEXT NOT NULL,
        blocked_by TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        evidence_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        started_at TIMESTAMPTZ NOT NULL,
        completed_at TIMESTAMPTZ,
        created_by TEXT NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, graph_run_id),
        FOREIGN KEY (tenant_id, workspace_id, graph_id) REFERENCES dojo_skill_graphs(tenant_id, workspace_id, graph_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        CHECK (mode IN ('practice', 'checkride', 'shadow', 'production')),
        CHECK (status IN ('completed', 'blocked', 'failed', 'paused'))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_license_versions (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        license_id TEXT NOT NULL,
        license_version TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        status TEXT NOT NULL,
        entrustment_level TEXT NOT NULL,
        readiness_level INTEGER NOT NULL,
        license_json JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_by TEXT,
        PRIMARY KEY (tenant_id, workspace_id, license_id, license_version),
        FOREIGN KEY (tenant_id, license_id) REFERENCES dojo_licenses(tenant_id, license_id) ON DELETE CASCADE,
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        CHECK (status IN ('active', 'expired', 'revoked', 'superseded')),
        CHECK (readiness_level >= 0 AND readiness_level <= 9)
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_checkride_runs (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        checkride_run_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        skill_version TEXT NOT NULL,
        graph_id TEXT,
        status TEXT NOT NULL,
        entrustment_level TEXT,
        readiness_level INTEGER,
        evidence_record_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        score_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        report_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        started_at TIMESTAMPTZ NOT NULL,
        completed_at TIMESTAMPTZ,
        created_by TEXT NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, checkride_run_id),
        FOREIGN KEY (tenant_id, skill_id, skill_version) REFERENCES dojo_skill_versions(tenant_id, skill_id, skill_version) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, workspace_id, graph_id) REFERENCES dojo_skill_graphs(tenant_id, workspace_id, graph_id) ON DELETE RESTRICT,
        CHECK (status IN ('queued', 'running', 'passed', 'failed', 'blocked', 'canceled')),
        CHECK (readiness_level IS NULL OR (readiness_level >= 0 AND readiness_level <= 9))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_scenario_runs (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        scenario_run_id TEXT NOT NULL,
        scenario_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        checkride_run_id TEXT,
        mutation_kind TEXT NOT NULL,
        status TEXT NOT NULL,
        fixture_sha256 TEXT,
        oracle_status TEXT NOT NULL,
        evidence_record_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        started_at TIMESTAMPTZ NOT NULL,
        completed_at TIMESTAMPTZ,
        created_by TEXT NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, scenario_run_id),
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, workspace_id, checkride_run_id) REFERENCES dojo_checkride_runs(tenant_id, workspace_id, checkride_run_id) ON DELETE RESTRICT,
        CHECK (status IN ('queued', 'running', 'passed', 'failed', 'blocked', 'needs_human', 'canceled')),
        CHECK (oracle_status IN ('pass', 'fail', 'block', 'needs_human')),
        CHECK (fixture_sha256 IS NULL OR fixture_sha256 ~ '^[A-Fa-f0-9]{64}$')
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_case_law (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        case_id TEXT NOT NULL,
        skill_id TEXT,
        title TEXT NOT NULL,
        finding TEXT NOT NULL,
        impact TEXT NOT NULL,
        rule_created TEXT NOT NULL,
        applies_to TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        binding_scope_kind TEXT NOT NULL,
        binding_scope_id TEXT NOT NULL,
        status TEXT NOT NULL,
        appeal_status TEXT NOT NULL DEFAULT 'none',
        reviewer TEXT,
        evidence_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        superseded_by TEXT,
        case_json JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, case_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        CHECK (binding_scope_kind IN ('tenant', 'organization', 'workspace', 'skill')),
        CHECK (status IN ('proposed', 'approved', 'deprecated')),
        CHECK (appeal_status IN ('none', 'requested', 'upheld', 'overturned')),
        CHECK (cardinality(evidence_refs) > 0)
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_antibodies (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        antibody_id TEXT NOT NULL,
        source_case_id TEXT,
        binding_scope_kind TEXT NOT NULL,
        binding_scope_id TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'proposed',
        pattern_sha256 TEXT NOT NULL,
        guardrail_predicate TEXT NOT NULL,
        evidence_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        antibody_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, workspace_id, antibody_id),
        FOREIGN KEY (tenant_id, workspace_id, source_case_id) REFERENCES dojo_case_law(tenant_id, workspace_id, case_id) ON DELETE RESTRICT,
        CHECK (binding_scope_kind IN ('tenant', 'organization', 'workspace', 'skill')),
        CHECK (status IN ('proposed', 'active', 'deprecated')),
        CHECK (pattern_sha256 ~ '^[A-Fa-f0-9]{64}$')
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_approvals (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        approval_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        license_id TEXT,
        workflow_id TEXT NOT NULL,
        license_version TEXT NOT NULL,
        current_entrustment_level TEXT NOT NULL,
        requested_action TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending',
        requested_by TEXT NOT NULL,
        requested_at TIMESTAMPTZ NOT NULL,
        reviewed_by TEXT,
        reviewed_at TIMESTAMPTZ,
        decision_reason TEXT,
        evidence_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        approval_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        PRIMARY KEY (tenant_id, workspace_id, approval_id),
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, license_id) REFERENCES dojo_licenses(tenant_id, license_id) ON DELETE RESTRICT,
        CHECK (status IN ('pending', 'approved', 'denied', 'superseded'))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_tool_registrations (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        tool_registration_id TEXT NOT NULL,
        tool_name TEXT NOT NULL,
        tool_version TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        license_id TEXT,
        manifest_digest TEXT NOT NULL,
        signed_manifest TEXT NOT NULL,
        proof_required BOOLEAN NOT NULL DEFAULT true,
        direct_call_policy TEXT NOT NULL DEFAULT 'blocked',
        status TEXT NOT NULL DEFAULT 'active',
        registered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        revoked_at TIMESTAMPTZ,
        manifest_json JSONB NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, tool_registration_id),
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, license_id) REFERENCES dojo_licenses(tenant_id, license_id) ON DELETE RESTRICT,
        UNIQUE (tenant_id, workspace_id, tool_name, tool_version),
        CHECK (manifest_digest ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (direct_call_policy IN ('blocked', 'dojo_dispatcher_only', 'practice_only')),
        CHECK (status IN ('active', 'revoked', 'superseded'))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_tool_invocations (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        invocation_id TEXT NOT NULL,
        tool_registration_id TEXT,
        tool_name TEXT NOT NULL,
        tool_version TEXT,
        skill_id TEXT,
        actor_id TEXT NOT NULL,
        actor_type TEXT NOT NULL,
        requested_action TEXT NOT NULL,
        status TEXT NOT NULL,
        proof_capsule_id TEXT,
        audit_event_id TEXT,
        invocation_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, workspace_id, invocation_id),
        FOREIGN KEY (tenant_id, workspace_id, tool_registration_id) REFERENCES dojo_tool_registrations(tenant_id, workspace_id, tool_registration_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        CHECK (actor_type IN ('human', 'agent', 'service')),
        CHECK (status IN ('allowed', 'blocked', 'failed', 'completed'))
      )`,
      `CREATE TABLE IF NOT EXISTS dojo_mcp_host_conformance_results (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        conformance_result_id TEXT NOT NULL,
        host_url TEXT NOT NULL,
        host_kind TEXT NOT NULL,
        status TEXT NOT NULL,
        report_sha256 TEXT NOT NULL,
        report_json JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_by TEXT NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, conformance_result_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        CHECK (host_kind IN ('local_loopback', 'deployed_non_loopback')),
        CHECK (status IN ('passed', 'failed', 'skipped')),
        CHECK (report_sha256 ~ '^[A-Fa-f0-9]{64}$')
      )`,
      "ALTER TABLE dojo_case_law ADD COLUMN IF NOT EXISTS applies_to TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[]",
      "ALTER TABLE dojo_approvals ADD COLUMN IF NOT EXISTS workflow_id TEXT NOT NULL DEFAULT ''",
      "ALTER TABLE dojo_approvals ADD COLUMN IF NOT EXISTS license_version TEXT NOT NULL DEFAULT ''",
      "ALTER TABLE dojo_approvals ADD COLUMN IF NOT EXISTS current_entrustment_level TEXT NOT NULL DEFAULT ''",
      "ALTER TABLE dojo_approvals ALTER COLUMN workflow_id DROP DEFAULT",
      "ALTER TABLE dojo_approvals ALTER COLUMN license_version DROP DEFAULT",
      "ALTER TABLE dojo_approvals ALTER COLUMN current_entrustment_level DROP DEFAULT",
      "CREATE INDEX IF NOT EXISTS dojo_app_releases_origin_idx ON dojo_app_releases (tenant_id, workspace_id, app_origin, app_version)",
      "CREATE INDEX IF NOT EXISTS dojo_source_snapshots_release_idx ON dojo_source_snapshots (tenant_id, workspace_id, app_release_id, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_source_tokens_locator_idx ON dojo_source_tokens (tenant_id, workspace_id, snapshot_id, stable_action_name)",
      "CREATE INDEX IF NOT EXISTS dojo_skill_graphs_skill_idx ON dojo_skill_graphs (tenant_id, workspace_id, skill_id, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_node_memories_status_idx ON dojo_node_memories (tenant_id, workspace_id, graph_id, status)",
      "CREATE INDEX IF NOT EXISTS dojo_graph_execution_runs_graph_idx ON dojo_graph_execution_runs (tenant_id, workspace_id, graph_id, started_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_graph_execution_runs_skill_idx ON dojo_graph_execution_runs (tenant_id, workspace_id, skill_id, started_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_license_versions_skill_idx ON dojo_license_versions (tenant_id, workspace_id, skill_id, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_checkride_runs_skill_idx ON dojo_checkride_runs (tenant_id, workspace_id, skill_id, started_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_scenario_runs_checkride_idx ON dojo_scenario_runs (tenant_id, workspace_id, checkride_run_id, started_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_case_law_scope_idx ON dojo_case_law (tenant_id, workspace_id, binding_scope_kind, binding_scope_id, status)",
      "CREATE INDEX IF NOT EXISTS dojo_case_law_applies_to_idx ON dojo_case_law USING GIN (applies_to)",
      "CREATE INDEX IF NOT EXISTS dojo_antibodies_scope_idx ON dojo_antibodies (tenant_id, workspace_id, binding_scope_kind, binding_scope_id, status)",
      "CREATE INDEX IF NOT EXISTS dojo_approvals_status_idx ON dojo_approvals (tenant_id, workspace_id, status, requested_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_approvals_workflow_idx ON dojo_approvals (tenant_id, workspace_id, workflow_id, requested_action)",
      "CREATE INDEX IF NOT EXISTS dojo_tool_registrations_tool_idx ON dojo_tool_registrations (tenant_id, workspace_id, tool_name, tool_version)",
      "CREATE INDEX IF NOT EXISTS dojo_tool_invocations_tool_idx ON dojo_tool_invocations (tenant_id, workspace_id, tool_name, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_mcp_host_conformance_status_idx ON dojo_mcp_host_conformance_results (tenant_id, workspace_id, host_kind, created_at DESC)",
    ],
  },
  {
    id: "005_dojo_ghost_shadow_evidence",
    description: "Create tenant-scoped Ghost Mode shadow evidence records with auditable non-mutating execution custody.",
    statements: [
      `CREATE TABLE IF NOT EXISTS dojo_ghost_shadow_evidence (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        evidence_id TEXT NOT NULL,
        run_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        workflow_id TEXT NOT NULL,
        license_id TEXT NOT NULL,
        action_matches BOOLEAN NOT NULL,
        license_status TEXT NOT NULL,
        guardrail_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        evidence_refs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
        evidence_json JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        created_by TEXT NOT NULL,
        request_id TEXT NOT NULL,
        correlation_id TEXT NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, evidence_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, skill_id) REFERENCES dojo_skills(tenant_id, skill_id) ON DELETE RESTRICT,
        FOREIGN KEY (tenant_id, license_id) REFERENCES dojo_licenses(tenant_id, license_id) ON DELETE RESTRICT,
        CHECK (license_status IN ('licensed', 'blocked')),
        CHECK (jsonb_typeof(evidence_json) = 'object'),
        CHECK (cardinality(evidence_refs) > 0)
      )`,
      "CREATE INDEX IF NOT EXISTS dojo_ghost_shadow_evidence_skill_idx ON dojo_ghost_shadow_evidence (tenant_id, workspace_id, skill_id, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_ghost_shadow_evidence_run_idx ON dojo_ghost_shadow_evidence (tenant_id, workspace_id, run_id)",
      "CREATE INDEX IF NOT EXISTS dojo_ghost_shadow_evidence_workflow_idx ON dojo_ghost_shadow_evidence (tenant_id, workspace_id, workflow_id, created_at DESC)",
    ],
  },
  {
    id: "006_dojo_proof_key_registry",
    description: "Create tenant-scoped proof key registry records for durable public verification and key rotation.",
    statements: [
      `CREATE TABLE IF NOT EXISTS dojo_proof_keys (
        tenant_id TEXT NOT NULL REFERENCES dojo_tenants(tenant_id) ON DELETE RESTRICT,
        key_id TEXT NOT NULL,
        issuer TEXT NOT NULL,
        algorithm TEXT NOT NULL,
        public_key_pem TEXT NOT NULL,
        status TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        rotated_at TIMESTAMPTZ,
        revoked_at TIMESTAMPTZ,
        retain_for_forensic_verification BOOLEAN NOT NULL DEFAULT false,
        key_json JSONB NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (tenant_id, key_id),
        CHECK (algorithm IN ('ed25519', 'hmac-sha256')),
        CHECK (status IN ('active', 'retired', 'revoked')),
        CHECK (jsonb_typeof(key_json) = 'object')
      )`,
      "CREATE INDEX IF NOT EXISTS dojo_proof_keys_active_idx ON dojo_proof_keys (tenant_id, issuer, algorithm, status, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_proof_keys_status_idx ON dojo_proof_keys (tenant_id, status, updated_at DESC)",
    ],
  },
  {
    id: "007_dojo_evidence_append_only_guards",
    description: "Install database-level append-only guards for evidence ledger records and checkpoints.",
    statements: [
      `CREATE OR REPLACE FUNCTION dojo_reject_evidence_ledger_mutation()
      RETURNS trigger
      LANGUAGE plpgsql
      AS $$
      BEGIN
        RAISE EXCEPTION 'dojo_evidence_ledger_append_only';
      END;
      $$`,
      `DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_trigger
          WHERE tgname = 'dojo_evidence_records_append_only'
            AND tgrelid = 'dojo_evidence_records'::regclass
        ) THEN
          CREATE TRIGGER dojo_evidence_records_append_only
          BEFORE UPDATE OR DELETE ON dojo_evidence_records
          FOR EACH ROW EXECUTE FUNCTION dojo_reject_evidence_ledger_mutation();
        END IF;
      END;
      $$`,
      `DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM pg_trigger
          WHERE tgname = 'dojo_ledger_checkpoints_append_only'
            AND tgrelid = 'dojo_ledger_checkpoints'::regclass
        ) THEN
          CREATE TRIGGER dojo_ledger_checkpoints_append_only
          BEFORE UPDATE OR DELETE ON dojo_ledger_checkpoints
          FOR EACH ROW EXECUTE FUNCTION dojo_reject_evidence_ledger_mutation();
        END IF;
      END;
      $$`,
    ],
  },
  {
    id: "008_dojo_therapeutic_runtime_states",
    description: "Create tenant-scoped therapeutic tomography runtime state records for production reconstruction.",
    statements: [
      `CREATE TABLE IF NOT EXISTS dojo_therapeutic_runtime_states (
        tenant_id TEXT NOT NULL,
        workspace_id TEXT NOT NULL,
        record_id TEXT NOT NULL,
        task_id TEXT NOT NULL,
        state_sha256 TEXT NOT NULL,
        state_text TEXT NOT NULL,
        state_json JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        created_by TEXT NOT NULL,
        PRIMARY KEY (tenant_id, workspace_id, record_id),
        FOREIGN KEY (tenant_id, workspace_id) REFERENCES dojo_workspaces(tenant_id, workspace_id) ON DELETE RESTRICT,
        CHECK (state_sha256 ~ '^[A-Fa-f0-9]{64}$'),
        CHECK (jsonb_typeof(state_json) = 'object')
      )`,
      "CREATE INDEX IF NOT EXISTS dojo_therapeutic_runtime_states_task_idx ON dojo_therapeutic_runtime_states (tenant_id, workspace_id, task_id, created_at DESC)",
      "CREATE INDEX IF NOT EXISTS dojo_therapeutic_runtime_states_created_idx ON dojo_therapeutic_runtime_states (tenant_id, workspace_id, created_at DESC)",
    ],
  },
];

export function dojoPostgresMigrationSql(migrations: DojoPostgresMigration[] = DOJO_POSTGRES_MIGRATIONS): string {
  assertUniqueMigrationIds(migrations);
  return migrations
    .flatMap((migration) => [
      `-- ${migration.id}: ${migration.description}`,
      ...migration.statements.map((statement) => `${trimSql(statement)};`),
    ])
    .join("\n\n") + "\n";
}

export function dojoPostgresMigrationStatements(
  migrations: DojoPostgresMigration[] = DOJO_POSTGRES_MIGRATIONS
): string[] {
  assertUniqueMigrationIds(migrations);
  return migrations.flatMap((migration) => migration.statements.map(trimSql));
}

export function assertUniqueMigrationIds(migrations: DojoPostgresMigration[]): void {
  const ids = new Set<string>();
  for (const migration of migrations) {
    if (ids.has(migration.id)) throw new Error(`duplicate_dojo_postgres_migration:${migration.id}`);
    ids.add(migration.id);
  }
}

function trimSql(sql: string): string {
  return sql
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .join("\n");
}
