apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-server
  namespace: synthi
spec:
  template:
    spec:
      containers:
        - name: collab
          env:
            - name: REDIS_URL
              value: null
              valueFrom:
                $patch: replace
                secretKeyRef:
                  name: synthi-secrets
                  key: REDIS_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signaling-server
  namespace: synthi
spec:
  template:
    spec:
      containers:
        - name: signaling
          env:
            - name: REDIS_URL
              value: null
              valueFrom:
                $patch: replace
                secretKeyRef:
                  name: synthi-secrets
                  key: REDIS_URL
