import { afterEach, describe, expect, it, vi } from 'vitest';
import { createNotebookContent, normalizeNotebook, parseNotebook, revisionOf } from '../notebook';
import { chooseSafeOutput, safeImageUrl } from '../outputSafety';
import { safeJupyterPath, validateJupyterOrigin } from '../policy';
import { compareNotebookRevisions, savePlan } from '../sync';
import { JupyterClient } from '../client';

describe('notebook model', () => {
  const notebook = { nbformat: 4, nbformat_minor: 5, metadata: { kernelspec: { name: 'python3' } }, cells: [{ cell_type: 'code', source: ['print(1)\n'], metadata: { custom: true }, execution_count: 1, outputs: [{ output_type: 'stream', name: 'stdout', text: '1\n' }] }] };
  it('preserves unknown metadata and normalizes source and ids', () => { const result = normalizeNotebook(notebook); expect(result.cells[0]).toMatchObject({ source: 'print(1)\n', metadata: { custom: true } }); expect(result.cells[0].id).toBeTruthy(); });
  it('rejects malformed notebooks', () => { expect(() => parseNotebook('{')).toThrow('malformed'); expect(() => normalizeNotebook({ nbformat: 4, cells: [{}] })).toThrow('unsupported type'); });
  it('creates valid nbformat content for a new notebook', () => { const result = parseNotebook(createNotebookContent()); expect(result).toMatchObject({ nbformat: 4, nbformat_minor: 5, metadata: { kernelspec: { name: 'python3' } } }); expect(result.cells).toHaveLength(1); expect(result.cells[0]).toMatchObject({ cell_type: 'code', source: '', outputs: [] }); });
  it('produces stable revision metadata', () => { expect(revisionOf('abc')).toEqual(revisionOf('abc')); expect(revisionOf('abc').hash).not.toBe(revisionOf('abd').hash); });
});
describe('output safety', () => { it('chooses only supported MIME types and bounds image URLs', () => { expect(chooseSafeOutput({ 'text/html': '<script />', 'text/plain': 'safe' })).toEqual({ mime: 'text/plain', value: 'safe' }); expect(safeImageUrl('image/svg+xml', 'abc')).toBeNull(); expect(safeImageUrl('image/png', 'abc')).toBe('data:image/png;base64,abc'); }); });
describe('gateway policy', () => { afterEach(() => vi.unstubAllEnvs()); it('rejects credential URLs and path traversal', () => { expect(() => validateJupyterOrigin('https://token@example.com')).toThrow(); expect(() => safeJupyterPath('../secret.ipynb')).toThrow(); expect(safeJupyterPath('notebooks/a.ipynb')).toBe('notebooks/a.ipynb'); }); it('allows the Docker host only when local Docker support is enabled', () => { expect(() => validateJupyterOrigin('http://host.docker.internal:8888')).toThrow(); vi.stubEnv('JUPYTER_ALLOW_DOCKER_HOST', '1'); expect(validateJupyterOrigin('http://host.docker.internal:8888')).toBe('http://host.docker.internal:8888'); }); });
describe('Jupyter server base paths', () => { it('uses a registered mount path for both HTTP and kernel channels', () => { const client = new JupyterClient({ origin: 'https://jupyter.example/', mountPath: '/team/lab/', token: 'secret' }); expect(client.endpointUrl('api/status')).toBe('https://jupyter.example/team/lab/api/status'); expect(client.mountPath).toBe('team/lab'); }); });
describe('sync coordination', () => { it('never resolves concurrent durable changes with last-write-wins', () => { const sync = compareNotebookRevisions({ baseline: { hash: 'base' }, workspace: { hash: 'local' }, server: { hash: 'remote' } }); expect(sync.state).toBe('conflict'); expect(savePlan({ sync })).toMatchObject({ allowed: false, recovery: 'choose_workspace_or_server' }); }); it('avoids duplicate writes for a mounted server', () => { expect(savePlan({ sync: { state: 'clean' }, mounted: true }).operations).toEqual(['workspace_write']); }); });
