/**
 * @fileoverview Synthi Editor Theme Bridge
 *
 * Previously this file exported a hardcoded SYNTHI_THEME constant.
 * The theme is now dynamically generated by the theme engine and
 * applied via ThemeProvider.  This module re-exports the static
 * fallback for backwards compatibility (used only as a default
 * before ThemeProvider mounts, and in tests).
 */
import synthiDark from '@/themes/builtin/synthi-dark.json';
import { generateMonacoTheme } from '@/lib/theme-engine';

/**
 * Static fallback Monaco theme – generated from the built-in Synthi Dark
 * JSON.  The live theme is managed by ThemeProvider.
 */
export const SYNTHI_THEME = generateMonacoTheme(synthiDark);
