import {
  ArchiveRestore,
  Bot,
  Cable,
  CircleGauge,
  ClipboardCheck,
  DatabaseZap,
  FileCheck2,
  FileJson,
  FileStack,
  FolderGit2,
  GitBranch,
  History,
  ListChecks,
  LockKeyhole,
  MapPinned,
  PackageCheck,
  SearchCheck,
  ServerCog,
  ShieldAlert,
  ShieldCheck,
  Siren,
  SquareActivity,
  Waypoints,
  Workflow,
} from "lucide-react";

export const CodeSiteIcons = Object.freeze({
  control: ServerCog,
  liveState: SquareActivity,
  workspaceGraph: Waypoints,
  paths: FolderGit2,
  agents: Bot,
  actions: ListChecks,
  approvals: ShieldCheck,
  governance: ClipboardCheck,
  planChanges: GitBranch,
  pathLocks: LockKeyhole,
  conflicts: ShieldAlert,
  evidence: FileCheck2,
  transactions: DatabaseZap,
  metrics: CircleGauge,
  activity: History,
  recovery: Siren,
  simulator: Workflow,
  quarantine: ArchiveRestore,
  inspections: ClipboardCheck,
  incidents: ShieldAlert,
  replay: History,
  artifacts: PackageCheck,
  files: FileStack,
  lineage: SearchCheck,
  scopes: MapPinned,
  signals: Cable,
  json: FileJson,
});
