import prisma from '@/lib/prisma';
import { encryptToken, decryptToken } from '@/lib/tokenCrypto';
import { resolveApprovedJupyterOrigin } from './policy';

function publicServer(row) { const { secret, secretId, ...server } = row; return { ...server, hasToken: Boolean(secret), tokenLast4: secret?.last4 || null }; }
export async function listJupyterServers(workspaceSlug) { return (await prisma.jupyterServer.findMany({ where: { workspaceSlug }, include: { secret: true }, orderBy: { createdAt: 'desc' } })).map(publicServer); }
export async function createJupyterServer({ workspaceSlug, name, origin, token = null, mountPath = '' }) { const approvedOrigin = await resolveApprovedJupyterOrigin(origin); const data = { name: String(name).trim().slice(0, 120), mountPath: String(mountPath || '').replace(/^\/+|\/+$/g, '') }; const existing = await prisma.jupyterServer.findUnique({ where: { workspaceSlug_origin: { workspaceSlug, origin: approvedOrigin } }, include: { secret: true } }); if (existing) { let replacementSecret = null; if (token) replacementSecret = await prisma.encryptedSecret.create({ data: { cipher: encryptToken(token), last4: token.slice(-4) } }); const updated = await prisma.jupyterServer.update({ where: { id: existing.id }, data: { ...data, ...(replacementSecret ? { secretId: replacementSecret.id } : {}) }, include: { secret: true } }); if (replacementSecret && existing.secretId) await prisma.encryptedSecret.delete({ where: { id: existing.secretId } }).catch(() => {}); return { server: publicServer(updated), reused: true }; } let secretId = null; if (token) { const secret = await prisma.encryptedSecret.create({ data: { cipher: encryptToken(token), last4: token.slice(-4) } }); secretId = secret.id; } return { server: publicServer(await prisma.jupyterServer.create({ data: { workspaceSlug, ...data, origin: approvedOrigin, secretId }, include: { secret: true } })), reused: false }; }
export async function getJupyterServer(id, workspaceSlug) { return prisma.jupyterServer.findFirst({ where: { id, workspaceSlug }, include: { secret: true } }); }
export async function resolveJupyterServer(id, workspaceSlug) { const row = await getJupyterServer(id, workspaceSlug); if (!row || !row.enabled) return null; return { ...row, token: row.secret ? decryptToken(row.secret.cipher) : null }; }
export async function revokeJupyterServer(id, workspaceSlug) { const row = await getJupyterServer(id, workspaceSlug); if (!row) return false; await prisma.jupyterServer.delete({ where: { id } }); if (row.secretId) await prisma.encryptedSecret.delete({ where: { id: row.secretId } }).catch(() => {}); return true; }
