export const RELEASE_BLOCKER_CATEGORIES = [
  "security",
  "frontend_transparency",
  "product",
];

export const RELEASE_BLOCKERS = [
  {
    id: "loopback_bind_only",
    category: "security",
    label: "Local API binds only to loopback",
    status: "implemented",
    evidence: ["rust:http::server_config_loopback_only", "security.rs::binds_only_loopback"],
  },
  {
    id: "non_loopback_bind_fails",
    category: "security",
    label: "Non-loopback bind fails",
    status: "implemented",
    evidence: ["rust:http::reject_non_loopback_bind", "security.rs::rejects_non_loopback_bind"],
  },
  {
    id: "random_local_port",
    category: "security",
    label: "Random local port",
    status: "implemented",
    evidence: ["rust:http::pick_ephemeral_loopback_port"],
  },
  {
    id: "auth_all_non_health",
    category: "security",
    label: "Auth required on all non-health endpoints",
    status: "implemented",
    evidence: ["rust:session::SessionGuard", "security.rs::non_health_requires_session"],
  },
  {
    id: "origin_validation",
    category: "security",
    label: "Origin validation",
    status: "implemented",
    evidence: ["rust:http::validate_origin", "synthi:api/local-support/httpGuards.test.js"],
  },
  {
    id: "csrf_signed_nonce",
    category: "security",
    label: "CSRF/signed nonce protection",
    status: "implemented",
    evidence: ["rust:session::signed_nonce", "synthi:request-envelope signature tests"],
  },
  {
    id: "fetch_metadata",
    category: "security",
    label: "Fetch Metadata checks",
    status: "implemented",
    evidence: ["synthi:api/local-support/httpGuards.test.js"],
  },
  {
    id: "pairing_ttl_rate_limits",
    category: "security",
    label: "Pairing code TTL and rate limits",
    status: "implemented",
    evidence: ["rust:pair::PairingChallengeStore", "security.rs::pairing_rate_limits"],
  },
  {
    id: "device_keypair_challenge",
    category: "security",
    label: "Device keypair challenge signing",
    status: "implemented",
    evidence: ["rust:pair::verify_device_challenge"],
  },
  {
    id: "pairing_fingerprint",
    category: "security",
    label: "Pairing fingerprint in browser and local app",
    status: "implemented",
    evidence: ["rust:pair::pairing_fingerprint", "synthi:LocalSupportTransparency"],
  },
  {
    id: "session_ttl",
    category: "security",
    label: "Session TTL",
    status: "implemented",
    evidence: ["rust:session::SessionStore", "security.rs::expires_sessions"],
  },
  {
    id: "request_replay_protection",
    category: "security",
    label: "Request replay protection",
    status: "implemented",
    evidence: ["synthi:controlPlane.enforceRequestEnvelopeReplayProtection"],
  },
  {
    id: "workspace_boundary",
    category: "security",
    label: "Workspace boundary enforcement",
    status: "implemented",
    evidence: ["rust:workspace::canonical_workspace_child"],
  },
  {
    id: "symlink_junction_escape_tests",
    category: "security",
    label: "Symlink/junction escape tests",
    status: "implemented",
    evidence: ["security.rs::blocks_symlink_escape", "security.rs::blocks_windows_junction_escape"],
  },
  {
    id: "denylist_local",
    category: "security",
    label: "Denylist enforced locally",
    status: "implemented",
    evidence: ["rust:workspace::LOCAL_SUPPORT_DENYLIST", "security.rs::blocks_default_ignored_artifacts"],
  },
  {
    id: "scanner_redactor",
    category: "security",
    label: "Scanner/redactor",
    status: "implemented",
    evidence: ["rust:scanner::scan_and_redact", "security.rs::redacts_secret_patterns"],
  },
  {
    id: "scanner_failure_denies",
    category: "security",
    label: "Scanner failure denies",
    status: "implemented",
    evidence: ["rust:scanner::ScannerDecision::Denied", "synthi:controlPlane precedence tests"],
  },
  {
    id: "no_shell_execution",
    category: "security",
    label: "No shell execution",
    status: "implemented",
    evidence: ["synthi:capability_blocked_in_mvp", "rust:ipc allowlist denies commands"],
  },
  {
    id: "no_filesystem_writes",
    category: "security",
    label: "No filesystem writes",
    status: "implemented",
    evidence: ["synthi:capability_blocked_in_mvp", "rust:workspace read-only APIs"],
  },
  {
    id: "no_full_repo_upload",
    category: "security",
    label: "No full repo upload",
    status: "implemented",
    evidence: ["synthi:workspace.repo.upload blocked", "rust:workspace request caps"],
  },
  {
    id: "no_broad_port_scan",
    category: "security",
    label: "No broad port scan",
    status: "implemented",
    evidence: ["rust:preview::explicit_port_approval_only"],
  },
  {
    id: "manual_port_approval",
    category: "security",
    label: "Manual port approval only",
    status: "implemented",
    evidence: ["rust:preview::approve_browser_port_grant", "synthi:ports revoke UI"],
  },
  {
    id: "host_based_preview_domain",
    category: "security",
    label: "Host-based preview domain",
    status: "implemented",
    evidence: ["rust:preview::PreviewTrafficGuard", "synthi:LocalSupportTransparency preview host"],
  },
  {
    id: "no_main_vectant_cookies_preview",
    category: "security",
    label: "No main Vectant cookies in preview",
    status: "implemented",
    evidence: ["rust:preview::sanitize_request_headers"],
  },
  {
    id: "response_header_policy",
    category: "security",
    label: "Response header policy",
    status: "implemented",
    evidence: ["rust:preview::harden_response_headers", "synthi:nextConfigHeaders.test.js"],
  },
  {
    id: "redirect_restrictions",
    category: "security",
    label: "Redirect restrictions",
    status: "implemented",
    evidence: ["rust:preview::classify_preview_redirect"],
  },
  {
    id: "service_workers_blocked",
    category: "security",
    label: "Service workers blocked",
    status: "implemented",
    evidence: ["synthi:preview service-worker route guards", "rust:preview header policy"],
  },
  {
    id: "flow_control_rate_limits",
    category: "security",
    label: "Flow control and rate limits",
    status: "implemented",
    evidence: ["rust:preview::PreviewTrafficGuard", "rust:http request body caps"],
  },
  {
    id: "signed_installer_update",
    category: "security",
    label: "Signed installer/update",
    status: "ci_required",
    evidence: ["rust:update::verify_signed_manifest", ".github/workflows/local-support-security.yml::SBOM"],
  },
  {
    id: "org_kill_switch",
    category: "security",
    label: "Org kill switch",
    status: "implemented",
    evidence: ["synthi:readLocalSupportPolicy org_kill_switch", "synthi:policy route tests"],
  },
  {
    id: "emergency_disable",
    category: "security",
    label: "Emergency disable",
    status: "implemented",
    evidence: ["synthi:emergency_controls", "rust:update version revocation"],
  },
  {
    id: "persistent_banner",
    category: "frontend_transparency",
    label: "Persistent banner",
    status: "implemented",
    evidence: ["synthi:LocalSupportTransparency sticky header"],
  },
  {
    id: "overview_screen",
    category: "frontend_transparency",
    label: "Overview screen",
    status: "implemented",
    evidence: ["tests/local-support-transparency.spec.ts::overview"],
  },
  {
    id: "context_inventory",
    category: "frontend_transparency",
    label: "Context inventory",
    status: "implemented",
    evidence: ["tests/local-support-transparency.spec.ts::inventory"],
  },
  {
    id: "sent_payload_history",
    category: "frontend_transparency",
    label: "Sent payload history",
    status: "implemented",
    evidence: ["tests/local-support-transparency.spec.ts::sent history"],
  },
  {
    id: "blocked_sensitive_items",
    category: "frontend_transparency",
    label: "Blocked sensitive items",
    status: "implemented",
    evidence: ["tests/local-support-transparency.spec.ts::blocked"],
  },
  {
    id: "redaction_summaries",
    category: "frontend_transparency",
    label: "Redaction summaries",
    status: "implemented",
    evidence: ["synthi:review before send redaction preview"],
  },
  {
    id: "review_before_send",
    category: "frontend_transparency",
    label: "Review-before-send",
    status: "implemented",
    evidence: ["synthi:LocalSupportTransparency review panel"],
  },
  {
    id: "activity_log",
    category: "frontend_transparency",
    label: "Activity log",
    status: "implemented",
    evidence: ["tests/local-support-transparency.spec.ts::activity"],
  },
  {
    id: "local_ports_screen",
    category: "frontend_transparency",
    label: "Local ports screen",
    status: "implemented",
    evidence: ["tests/local-support-transparency.spec.ts::ports"],
  },
  {
    id: "permission_mode_screen",
    category: "frontend_transparency",
    label: "Permission mode screen",
    status: "implemented",
    evidence: ["tests/local-support-transparency.spec.ts::permission mode"],
  },
  {
    id: "pause_visible",
    category: "frontend_transparency",
    label: "Pause visible everywhere",
    status: "implemented",
    evidence: ["synthi:sticky header Pause"],
  },
  {
    id: "disconnect_visible",
    category: "frontend_transparency",
    label: "Disconnect visible everywhere",
    status: "implemented",
    evidence: ["synthi:sticky header Disconnect"],
  },
  {
    id: "revoke_controls",
    category: "frontend_transparency",
    label: "Revoke controls",
    status: "implemented",
    evidence: ["synthi:port revoke", "synthi:session approvals revoke"],
  },
  {
    id: "export_delete_local_history",
    category: "frontend_transparency",
    label: "Export/delete local history",
    status: "implemented",
    evidence: ["tests/local-support-transparency.spec.ts::exports scrubbed history"],
  },
  {
    id: "clear_actor_identity",
    category: "frontend_transparency",
    label: "Clear actor identity on requests",
    status: "implemented",
    evidence: ["synthi:sentPayloads actor column", "synthi:request envelope actor validation"],
  },
  {
    id: "available_vs_sent",
    category: "frontend_transparency",
    label: "Users can distinguish available vs sent",
    status: "implemented",
    evidence: ["tests/local-support-transparency.spec.ts::available locally copy"],
  },
  {
    id: "onboarding_explains_risks",
    category: "product",
    label: "Onboarding explains risks",
    status: "implemented",
    evidence: ["synthi:workspace selection setup checklist", "synthi:review before send copy"],
  },
  {
    id: "workspace_picker_complete",
    category: "product",
    label: "Workspace picker complete",
    status: "implemented",
    evidence: ["synthi:workspace selection panel", "rust:workspace canonicalization"],
  },
  {
    id: "balanced_default",
    category: "product",
    label: "Balanced mode default",
    status: "implemented",
    evidence: ["synthi:readLocalSupportPolicy mvp.balanced_mode_default"],
  },
  {
    id: "manual_mode_available",
    category: "product",
    label: "Manual mode available",
    status: "implemented",
    evidence: ["synthi:permissionModes Manual mode"],
  },
  {
    id: "fast_support_disabled",
    category: "product",
    label: "Fast Support disabled or strictly controlled",
    status: "implemented",
    evidence: ["synthi:Fast Support Disabled", "synthi:readLocalSupportPolicy fast_support_enabled default false"],
  },
  {
    id: "agent_read_disabled",
    category: "product",
    label: "Agent read disabled in MVP",
    status: "implemented",
    evidence: ["synthi:capability_blocked_in_mvp", "synthi:ports capability flags"],
  },
  {
    id: "agent_interaction_disabled",
    category: "product",
    label: "Agent interaction disabled in MVP",
    status: "implemented",
    evidence: ["synthi:browser interaction capability blocked"],
  },
  {
    id: "error_states_understandable",
    category: "product",
    label: "Error states understandable",
    status: "implemented",
    evidence: ["synthi:policy route disabled reason", "synthi:LocalSupportTransparency disabled labels"],
  },
  {
    id: "uninstall_stops_bridge",
    category: "product",
    label: "Uninstall stops local bridge",
    status: "implemented",
    evidence: ["rust:lifecycle::uninstall_cleanup"],
  },
  {
    id: "update_required_state",
    category: "product",
    label: "Update-required state implemented",
    status: "implemented",
    evidence: ["synthi:app_version_too_old", "synthi:Update required below 0.1.0"],
  },
];

export const RED_TEAM_SCENARIOS = [
  ["malicious_website_localhost_attack", "Malicious website localhost attack", "origin_fetch_metadata_csrf"],
  ["compromised_support_session", "Compromised support session", "signed_envelopes_replay_policy_precedence"],
  ["malicious_repo_symlink_farm", "Malicious repo symlink farm", "workspace_boundary_symlink_junction_tests"],
  ["malicious_local_dev_server", "Malicious local dev server", "preview_header_redirect_rate_limits"],
  ["preview_ssrf_attempt", "Preview SSRF attempt", "redirect_private_network_blocks"],
  ["secret_heavy_logs", "Secret-heavy logs", "scanner_redactor_review_before_send"],
  ["update_downgrade_attempt", "Update downgrade attempt", "signed_update_revocation_min_version"],
  ["endpoint_fuzzing", "Endpoint fuzzing", "schema_size_and_capability_denials"],
  ["websocket_abuse", "WebSocket abuse", "preview_upgrade_denial"],
  ["confused_deputy_approval_flow", "Confused-deputy approval flow", "policy_precedence_final_scanner_denial"],
].map(([id, label, evidence]) => ({
  id,
  label,
  status: "covered",
  evidence,
}));

export function summarizeLocalSupportReleaseReadiness(blockers = RELEASE_BLOCKERS) {
  const byCategory = Object.fromEntries(RELEASE_BLOCKER_CATEGORIES.map((category) => [category, 0]));
  const byStatus = {};
  for (const blocker of blockers) {
    byCategory[blocker.category] = (byCategory[blocker.category] || 0) + 1;
    byStatus[blocker.status] = (byStatus[blocker.status] || 0) + 1;
  }

  return {
    total: blockers.length,
    byCategory,
    byStatus,
    mapped: blockers.filter((blocker) => Array.isArray(blocker.evidence) && blocker.evidence.length > 0).length,
    unmapped: blockers.filter((blocker) => !Array.isArray(blocker.evidence) || blocker.evidence.length === 0),
  };
}
