#!/usr/bin/env bash
# ============================================================================
# EXECUTED SHADOW MERGE PROOF (plan Workstream E, §9.4 executed mode)
#
# Everything in this script is derived at runtime from live state:
#  - the repo + base commit are created inside the container and read back via git
#  - the patch is GENERATED by git itself (git diff between real commits)
#  - the digest is computed from those exact bytes
#  - the validation command asserts the patched content produced by the merge
# No hardcoded digests, paths outside the declared env, or authored outcomes.
# ============================================================================
set -uo pipefail
cd "C:/Users/polek/Desktop/vectant-ade" || exit 1

BASE="${BASE:-http://localhost:3000}"
WS="${PROOF_WS:-acme-shadow-exec}"
OUT="$LOCALAPPDATA/Temp/shadow-exec-proof"
mkdir -p "$OUT"
AUTH="Authorization: Bearer $(grep -E '^SYNTHI_CODESITE_TOKEN=' .env.local | head -1 | cut -d= -f2-)"
JSON='Content-Type: application/json'
PASS=0; FAIL=0

ok()  { PASS=$((PASS+1)); echo "  PASS: $1"; }
bad() { FAIL=$((FAIL+1)); echo "  FAIL: $1"; }
check() { local name="$1" got="$2" want="$3"; [ "$got" = "$want" ] && ok "$name ($got)" || bad "$name (got $got want $want)"; }

jget() { node -e "
let d='';process.stdin.on('data',c=>d+=c).on('end',()=>{
  const parts=process.argv[1].split('.');let o=JSON.parse(d);
  for(const p of parts){o=o&&o[p];}
  console.log(o===undefined||o===null?'':(typeof o==='object'?JSON.stringify(o):o));
})" "$1"; }

echo "=== Setup: project on the live control plane ==="
HTTP=$(curl -s -o "$OUT/proj.json" -w '%{http_code}' -X POST "$BASE/api/workspace/$WS/codesite/projects" -H "$AUTH" -H "$JSON" -d '{"title":"Rotation v2 executable merge"}')
check "project created" "$HTTP" "201"
PID=$(cat "$OUT/proj.json" | jget project.id)

echo "=== Create a real repo + a real second commit inside the runner root ==="
docker exec vectant-ade-frontend-1 sh -c '
set -e
rm -rf /workspace-shadow/shadow-repo
mkdir -p /workspace-shadow/shadow-repo/contracts
cd /workspace-shadow/shadow-repo
git init -q .
git config user.email runner@codesite.local && git config user.name "CodeSite Runner"
printf "{\n  \"version\": 1\n}\n" > contracts/rotation-event.json
git add -A && git commit -qm "base: rotation v1"
printf "{\n  \"version\": 2\n}\n" > contracts/rotation-event.json
git add -A && git commit -qm "producer: rotation v2"
printf "BASE=%s\nHEAD=%s\n" "$(git rev-parse HEAD~1)" "$(git rev-parse HEAD)"
' > "$OUT/commits.txt" 2>"$OUT/repoerr.txt"
BASE_COMMIT=$(grep '^BASE=' "$OUT/commits.txt" | cut -d= -f2 | tr -d '\r\n ')
HEAD_COMMIT=$(grep '^HEAD=' "$OUT/commits.txt" | cut -d= -f2 | tr -d '\r\n ')
[ ${#BASE_COMMIT} = 40 ] && [ ${#HEAD_COMMIT} = 40 ] \
  && ok "real commits recorded: base=${BASE_COMMIT:0:10} head=${HEAD_COMMIT:0:10}" \
  || { bad "commit capture failed"; cat "$OUT/repoerr.txt"; exit 1; }

echo "=== Derive the patch bytes from git itself ==="
docker exec vectant-ade-frontend-1 sh -c '
cd /workspace-shadow/shadow-repo && git diff --binary --full-index HEAD~1 HEAD
' > "$OUT/change.patch" 2>/dev/null
[ -s "$OUT/change.patch" ] && ok "patch derived from live repo ($(wc -c < "$OUT/change.patch") bytes)" || bad "empty patch from git diff"

node -e "
const c=require('crypto');
const fs=require('fs');
const patch=fs.readFileSync(process.argv[1],'utf8');
const digestHex='sha256:'+c.createHash('sha256').update(Buffer.from(patch,'utf8')).digest('hex');
const body={
  shadowJobRef:'shadow-exec-'+Date.now(),
  baseSnapshot:'repo@'+process.argv[2].slice(0,12),
  requireExternalRunnerEvidence:true,
  proofMaturity:'mature',
  shadowExecutionPlan:{
    repoRoot:'/workspace-shadow/shadow-repo',
    baseCommit:process.argv[2],
    // The command reads the worktree file AFTER the patch applied and fails
    // if the merge did not really produce version 2.
    patchArtifacts:[{id:'rotation-v2-patch',digest:digestHex,content:patch}],
    commands:[{label:'postmerge-version-check',command:'node',args:['-e','const fs=require(\"fs\");const v=JSON.parse(fs.readFileSync(\"contracts/rotation-event.json\",\"utf8\")).version;if(v!==2){process.exit(3)}console.log(\"contract v2 OK\")']}]
  },
  universes:[{strategy:'producer-first'},{strategy:'consumer-first'}]
};
fs.writeFileSync(process.argv[3],JSON.stringify(body));
console.log('patch digest:',digestHex);
" "$(cygpath -w "$OUT/change.patch")" "$BASE_COMMIT" "$(cygpath -w "$OUT/simbody.json")"

echo "=== Executed shadow merge with external-runner evidence required ==="
HTTP=$(curl -s -o "$OUT/sim.json" -w '%{http_code}' -X POST "$BASE/api/workspace/$WS/codesite/projects/$PID/shadow-merge-simulate" -H "$AUTH" -H "$JSON" -d @"$OUT/simbody.json")
check "executed shadow merge accepted" "$HTTP" "200"
RESULTKIND=$(cat "$OUT/sim.json" | jget resultKind)
check "resultKind executed" "$RESULTKIND" "executed"
EXECMODE=$(cat "$OUT/sim.json" | jget reason.shadowExecutionMode)
check "shadowExecutionMode external_runner" "$EXECMODE" "external_runner"
EXSTATUS=$(cat "$OUT/sim.json" | jget shadowExecution.status)
check "shadowExecution.status completed" "$EXSTATUS" "completed"

UNIV_OK=$(node -e "
const d=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'));
// Executed universes are merged into the simulated ones under .execution
// (mergeExecutedShadowUniverses); the runner's own reason codes prove the
// worktree was materialized, patch applied, and commands run.
const u=(d.universes||[]).find(x=>x.execution
  && (x.execution.evidenceRefs||[]).some(r=>String(r).includes('shadow-after-tree'))
  && (x.reasonCodes||[]).includes('shadow_universe_repo_commands_passed'));
console.log(u?'yes':'no');
" "$(cygpath -w "$OUT/sim.json")")
check "universe executed+materialized+applied with command evidence" "$UNIV_OK" "yes"

CMDSTATUS=$(node -e "
const d=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'));
const u=(d.universes||[]).find(x=>x.execution);
console.log(u?(u.execution.status==='passed'?'passed':'not-passed'):'none');
" "$(cygpath -w "$OUT/sim.json")")
check "post-merge command passed inside worktree" "$CMDSTATUS" "passed"

TREE_EVIDENCE=$(node -e "
const d=JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'));
const u=(d.universes||[]).find(x=>x.execution);
const refs=(u?.execution?.evidenceRefs)||[];
const before=refs.find(r=>r.includes('shadow-before-tree:'));
const after=refs.find(r=>r.includes('shadow-after-tree:'));
console.log(before&&after&&before!==after?'trees-differ':'missing');
" "$(cygpath -w "$OUT/sim.json")")
check "before/after tree evidence captured and distinct" "$TREE_EVIDENCE" "trees-differ"

RUNTIME_MS=$(cat "$OUT/sim.json" | jget shadowExecution.runtimeMs)
[ -n "$RUNTIME_MS" ] && [ "$RUNTIME_MS" != "0" ] && ok "runtime evidence captured (runtimeMs=$RUNTIME_MS)" || bad "no runtime evidence"

echo "=== Negative A: tampered patch digest must fail closed ==="
node -e "
const fs=require('fs');
const body=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));
body.shadowJobRef='shadow-tamper-'+Date.now();
body.shadowExecutionPlan.patchArtifacts[0].digest='sha256:'+('0'.repeat(64));
body.shadowExecutionPlan.commands=[];
fs.writeFileSync(process.argv[2],JSON.stringify(body));
" "$(cygpath -w "$OUT/simbody.json")" "$(cygpath -w "$OUT/tamperbody.json")"
HTTP=$(curl -s -o "$OUT/tamper.json" -w '%{http_code}' -X POST "$BASE/api/workspace/$WS/codesite/projects/$PID/shadow-merge-simulate" -H "$AUTH" -H "$JSON" -d @"$OUT/tamperbody.json")
[ "$HTTP" = "400" ] && ok "tampered digest rejected ($HTTP)" || bad "tampered digest NOT rejected ($HTTP)"
grep -qE "digest_mismatch|preimage|evidence_required" "$OUT/tamper.json" && ok "rejection cites verification failure" || bad "unexpected error body"

echo "=== Negative B: preimage mismatch (patch vs different base) must fail ==="
node -e "
const fs=require('fs');
const body=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));
// point at a fresh repo whose content does NOT match the patch preimage
body.shadowJobRef='shadow-preimage-'+Date.now();
fs.writeFileSync(process.argv[2],JSON.stringify(body));
" "$(cygpath -w "$OUT/simbody.json")" "$(cygpath -w "$OUT/preimagebody.json")"
docker exec vectant-ade-frontend-1 sh -c '
rm -rf /workspace-shadow/mismatch-repo && mkdir -p /workspace-shadow/mismatch-repo/contracts
cd /workspace-shadow/mismatch-repo
git init -q .
git config user.email r@l && git config user.name R
printf "{\n  \"version\": 99\n}\n" > contracts/rotation-event.json
git add -A && git commit -qm unrelated
git rev-parse HEAD
' > "$OUT/mismatchbase.txt" 2>/dev/null
MISMATCH_BASE=$(tr -d '\r\n ' < "$OUT/mismatchbase.txt")
node -e "
const fs=require('fs');
const body=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));
body.shadowExecutionPlan.repoRoot='/workspace-shadow/mismatch-repo';
body.shadowExecutionPlan.baseCommit=process.argv[2];
fs.writeFileSync(process.argv[1],JSON.stringify(body));
" "$(cygpath -w "$OUT/preimagebody.json")" "$MISMATCH_BASE"
HTTP=$(curl -s -o "$OUT/preimage.json" -w '%{http_code}' -X POST "$BASE/api/workspace/$WS/codesite/projects/$PID/shadow-merge-simulate" -H "$AUTH" -H "$JSON" -d @"$OUT/preimagebody.json")
[ "$HTTP" = "400" ] && ok "preimage mismatch rejected ($HTTP)" || bad "preimage mismatch NOT rejected ($HTTP)"
grep -qE "preimage|apply|evidence_required" "$OUT/preimage.json" && ok "rejection cites preimage check" || bad "unexpected error body"

echo ""
echo "=== SUMMARY ==="
echo "PASS=$PASS FAIL=$FAIL"
[ "$FAIL" = "0" ] && echo "EXECUTED SHADOW MERGE PROOF: PASSED" || echo "EXECUTED SHADOW MERGE PROOF: FAILED"
