import "./globals.css";
import "./editor-overrides.css";
import { Geist, Geist_Mono } from "next/font/google";
import NextAuthSessionProvider from "./SessionProvider";
import { ReduxProvider } from "./ReduxProvider";
import { Toaster } from "../components/ui/sonner";
import GlobalErrorHandler from "../components/GlobalErrorHandler";
import StoreHydrator from "../components/StoreHydrator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <GlobalErrorHandler />
        <ReduxProvider>
          <StoreHydrator />
          <NextAuthSessionProvider>
            {children}
          </NextAuthSessionProvider>
        </ReduxProvider>
        
        
      </body>
    </html>
  );
}
