'use client';
import { useCallback, useEffect, useState } from 'react';
import { Link2, Plus, Trash2 } from 'lucide-react';
import { useAppSelector } from '@/redux/hooks';

export default function JupyterConnectionSettings() {
  const slug = useAppSelector((state) => state.workspace.slug); const [servers, setServers] = useState([]); const [form, setForm] = useState({ name: '', origin: '', token: '', mountPath: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!slug) return; const response = await fetch(`/api/workspace/${encodeURIComponent(slug)}/jupyter/servers`); if (response.ok) setServers((await response.json()).servers || []); }, [slug]);
  useEffect(() => { load(); }, [load]);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch(`/api/workspace/${encodeURIComponent(slug)}/jupyter/servers`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Connection could not be saved'); setForm({ name: '', origin: '', token: '', mountPath: '' }); await load(); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  const test = async (id) => { setError(''); setBusy(true); try { const response = await fetch(`/api/workspace/${encodeURIComponent(slug)}/jupyter/servers/${encodeURIComponent(id)}/test`, { method: 'POST' }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Connection test failed'); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  const revoke = async (id) => { if (!confirm('Revoke this Jupyter server? Existing kernels are not terminated.')) return; await fetch(`/api/workspace/${encodeURIComponent(slug)}/jupyter/servers/${encodeURIComponent(id)}`, { method: 'DELETE' }); await load(); };
  if (!slug) return null;
  return <section className="mt-4 pt-3 border-t" style={{ borderColor: 'var(--border-subtle)' }}><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}><Link2 size={14}/> Jupyter servers</div><p className="mt-1 text-[11px] leading-relaxed" style={{ color: 'var(--text-muted)' }}>Connect an already-running server for this workspace. Tokens are encrypted server-side and never stored in the browser.</p>{servers.map((server) => <div key={server.id} className="mt-2 flex items-center justify-between gap-2 px-2 py-1.5 rounded" style={{ background: 'var(--bg-input, var(--bg-editor))' }}><div className="min-w-0"><strong className="block text-xs truncate">{server.name}</strong><span className="text-[10px] truncate block" style={{ color: 'var(--text-muted)' }}>{server.origin}{server.hasToken ? ` · token ••••${server.tokenLast4}` : ''}</span></div><div className="flex gap-1"><button disabled={busy} className="p-1 text-[10px]" onClick={() => test(server.id)}>Test</button><button aria-label={`Revoke ${server.name}`} className="p-1" onClick={() => revoke(server.id)}><Trash2 size={14}/></button></div></div>)}<form onSubmit={submit} className="mt-2 grid gap-1.5"><input required placeholder="Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/><input required type="url" placeholder="https://jupyter.example" value={form.origin} onChange={(e) => setForm({ ...form, origin: e.target.value })}/><input type="password" autoComplete="off" placeholder="Token (optional)" value={form.token} onChange={(e) => setForm({ ...form, token: e.target.value })}/><input placeholder="Workspace mount path (optional)" value={form.mountPath} onChange={(e) => setForm({ ...form, mountPath: e.target.value })}/>{error && <p role="alert" className="text-[11px] text-red-400">{error}</p>}<button disabled={busy} className="inline-flex items-center justify-center gap-1.5 rounded px-2 py-1.5 text-xs" style={{ background: 'var(--accent-primary)', color: 'var(--bg-editor)' }}><Plus size={14}/>{busy ? 'Saving…' : 'Add server'}</button></form></section>;
}
