// ============================================================
// SYNTHI GPU RUNTIME CONTRACT HEADER
// ============================================================
//
// The GPU HMR ABI is a real C/C++ header surface, not only prompt text.
// The Kernel Splitter Agent is taught to include this header from
// shared.h, while the worker writes the header into the workspace before
// compiling GPU-enabled projects. The actual function implementations live
// in the Synthi host runner / runtime boundary; this file gives core.cpp
// and host_runner.cpp a stable declaration set.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

use crate::hmr::compile_manifest::{DeviceVendor, GpuBuildBlock};

pub const SYNTHI_GPU_RUNTIME_HEADER: &str = "synthi_gpu_runtime.h";

pub fn render_gpu_runtime_header(gpu: &GpuBuildBlock) -> String {
    let vendor_define = match gpu.vendor {
        DeviceVendor::Cuda => "#define SYNTHI_GPU_VENDOR_CUDA 1\n#define SYNTHI_GPU_VENDOR_ROCM 0",
        DeviceVendor::Rocm => "#define SYNTHI_GPU_VENDOR_CUDA 0\n#define SYNTHI_GPU_VENDOR_ROCM 1",
    };
    let vendor_string = gpu.vendor.as_str();

    format!(
        r#"#pragma once
// Generated by Synthi. Do not edit by hand.
// Runtime contract for GPU HMR sidecar modules.

#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <type_traits>

{vendor_define}
#define SYNTHI_GPU_VENDOR "{vendor_string}"

extern "C" {{

struct DeviceDescriptor {{
    const char* vendor;
    const char* const* arches;
    const char* const* kernels;
    int num_arches;
    int num_kernels;
    int constant_layout_bytes;
}};

struct SynthiGpuRuntime;

const DeviceDescriptor* device_descriptor();
void device_on_load(const unsigned char* prev_blob, std::size_t len);
std::size_t device_save_size();
void device_save_write(unsigned char* out, std::size_t cap);
unsigned long long device_kernel_sig_hash(const char* name);

bool synthi_gpu_launch_raw(
    SynthiGpuRuntime* gpu,
    const char* kernel_name,
    const void* grid,
    std::size_t grid_size,
    const void* block,
    std::size_t block_size,
    std::size_t shared_bytes,
    std::uintptr_t stream_token,
    const void* const* args,
    std::size_t arg_count);

std::uint64_t synthi_gpu_launch_generation();

bool synthi_gpu_launch_raw_checked(
    SynthiGpuRuntime* gpu,
    const char* kernel_name,
    const void* grid,
    std::size_t grid_size,
    const void* block,
    std::size_t block_size,
    std::size_t shared_bytes,
    std::uintptr_t stream_token,
    const void* const* args,
    std::size_t arg_count,
    std::uint64_t expected_generation);

void synthi_gpu_register_buffer(
    SynthiGpuRuntime* gpu,
    void* ptr,
    std::size_t bytes,
    const char* semantic_name,
    const char* lifetime_hint);

bool synthi_gpu_pack_buffer(const char* semantic_name, const void* ptr, std::size_t bytes);
bool synthi_gpu_restore_buffer(const unsigned char* blob, const char* semantic_name, void** out_ptr);

}} // extern "C"

struct SynthiGpuLaunchTable {{
    std::uint64_t generation;
    bool (*launch_raw)(
        SynthiGpuRuntime*,
        const char*,
        const void*,
        std::size_t,
        const void*,
        std::size_t,
        std::size_t,
        std::uintptr_t,
        const void* const*,
        std::size_t,
        std::uint64_t);
}};

inline SynthiGpuLaunchTable synthi_gpu_launch_table() {{
    return SynthiGpuLaunchTable{{
        synthi_gpu_launch_generation(),
        &synthi_gpu_launch_raw_checked,
    }};
}}

inline std::uintptr_t synthi_gpu_stream_token(std::nullptr_t) {{
    return 0;
}}

template <typename Stream>
inline std::uintptr_t synthi_gpu_stream_token(Stream stream) {{
    if constexpr (std::is_pointer_v<Stream>) {{
        return reinterpret_cast<std::uintptr_t>(stream);
    }} else {{
        return static_cast<std::uintptr_t>(stream);
    }}
}}

template <typename Grid, typename Block, typename Stream>
inline bool synthi_gpu_launch(
    SynthiGpuRuntime* gpu,
    const char* kernel_name,
    const Grid& grid,
    const Block& block,
    std::size_t shared_bytes,
    Stream stream,
    std::initializer_list<const void*> args) {{
    const SynthiGpuLaunchTable table = synthi_gpu_launch_table();
    return table.launch_raw(
        gpu,
        kernel_name,
        static_cast<const void*>(&grid),
        sizeof(Grid),
        static_cast<const void*>(&block),
        sizeof(Block),
        shared_bytes,
        synthi_gpu_stream_token(stream),
        args.begin(),
        args.size(),
        table.generation);
}}

inline void synthi_register(
    SynthiGpuRuntime* gpu,
    void* ptr,
    std::size_t bytes,
    const char* semantic_name,
    const char* lifetime_hint) {{
    synthi_gpu_register_buffer(gpu, ptr, bytes, semantic_name, lifetime_hint);
}}

inline void synthi_register(void* ptr, std::size_t bytes, const char* lifetime_hint) {{
    synthi_gpu_register_buffer(nullptr, ptr, bytes, nullptr, lifetime_hint);
}}
"#
    )
}

pub async fn ensure_gpu_runtime_contract_header(
    workspace_dir: &Path,
    gpu: &GpuBuildBlock,
) -> Result<PathBuf> {
    let body = render_gpu_runtime_header(gpu);
    let path = workspace_dir.join(SYNTHI_GPU_RUNTIME_HEADER);
    tokio::fs::write(&path, &body)
        .await
        .with_context(|| format!("writing {}", path.display()))?;
    let internal_path = workspace_dir
        .join(".synthi")
        .join("generated")
        .join("gpu")
        .join(SYNTHI_GPU_RUNTIME_HEADER);
    if let Some(parent) = internal_path.parent() {
        tokio::fs::create_dir_all(parent)
            .await
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    tokio::fs::write(&internal_path, &body)
        .await
        .with_context(|| format!("writing {}", internal_path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hmr::compile_manifest::{
        DeviceCompiler, FatbinStrategy, GpuBuildBlock, SnapshotMode,
    };
    use std::fs;
    use std::process::Command;

    fn gpu(vendor: DeviceVendor) -> GpuBuildBlock {
        GpuBuildBlock {
            vendor,
            device_compiler: match vendor {
                DeviceVendor::Cuda => DeviceCompiler::Nvcc,
                DeviceVendor::Rocm => DeviceCompiler::Hipcc,
            },
            arch: vec!["sm_80".to_string()],
            device_flags: vec![],
            runtime_libs: vec![],
            snapshot_mode: SnapshotMode::Auto,
            fatbin_strategy: FatbinStrategy::SidecarModule,
        }
    }

    #[test]
    fn header_declares_launch_and_lifecycle_contract() {
        let h = render_gpu_runtime_header(&gpu(DeviceVendor::Cuda));
        assert!(h.contains("synthi_gpu_launch_raw"));
        assert!(h.contains("synthi_gpu_launch_raw_checked"));
        assert!(h.contains("SynthiGpuLaunchTable"));
        assert!(h.contains("inline bool synthi_gpu_launch"));
        assert!(h.contains("synthi_gpu_stream_token(std::nullptr_t)"));
        assert!(h.contains("const DeviceDescriptor* device_descriptor()"));
        assert!(h.contains("void device_on_load"));
        assert!(h.contains("std::size_t device_save_size()"));
        assert!(h.contains("void device_save_write"));
        assert!(h.contains("unsigned long long device_kernel_sig_hash"));
    }

    #[test]
    fn header_is_vendor_specific_without_cuda_or_hip_headers() {
        let cuda = render_gpu_runtime_header(&gpu(DeviceVendor::Cuda));
        let rocm = render_gpu_runtime_header(&gpu(DeviceVendor::Rocm));
        assert!(cuda.contains("#define SYNTHI_GPU_VENDOR_CUDA 1"));
        assert!(rocm.contains("#define SYNTHI_GPU_VENDOR_ROCM 1"));
        assert!(!cuda.contains("cuda_runtime.h"));
        assert!(!rocm.contains("hip/hip_runtime.h"));
    }

    #[test]
    fn generated_header_accepts_common_stream_token_shapes() {
        let dir = tempfile::tempdir().unwrap();
        let header_path = dir.path().join(SYNTHI_GPU_RUNTIME_HEADER);
        let smoke_path = dir.path().join("stream_token_smoke.cpp");
        fs::write(
            &header_path,
            render_gpu_runtime_header(&gpu(DeviceVendor::Cuda)),
        )
        .unwrap();
        fs::write(
            &smoke_path,
            r#"#include "synthi_gpu_runtime.h"

struct Dim3 { unsigned int x; unsigned int y; unsigned int z; };

void smoke(SynthiGpuRuntime* gpu) {
    Dim3 grid{1, 1, 1};
    Dim3 block{32, 1, 1};
    int value = 0;
    const void* arg = &value;
    (void)synthi_gpu_stream_token(nullptr);
    (void)synthi_gpu_stream_token(static_cast<void*>(nullptr));
    (void)synthi_gpu_stream_token(0);
    (void)synthi_gpu_launch(gpu, "noop", grid, block, 0, nullptr, {arg});
}
"#,
        )
        .unwrap();

        let compiler = std::env::var("CXX").unwrap_or_else(|_| "c++".to_string());
        let output = Command::new(&compiler)
            .arg("-std=c++17")
            .arg("-fsyntax-only")
            .arg("-I")
            .arg(dir.path())
            .arg(&smoke_path)
            .output()
            .unwrap_or_else(|err| panic!("failed to run {compiler}: {err}"));

        assert!(
            output.status.success(),
            "generated GPU runtime header failed C++ syntax check\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
