// ============================================================
// SYNTHI GPU RUNTIME CONTRACT HEADER
// ============================================================
//
// The GPU HMR ABI is a real C/C++ header surface, not only prompt text.
// The Kernel Splitter Agent is taught to include this header from
// shared.h, while the worker writes the header into the workspace before
// compiling GPU-enabled projects. The actual function implementations live
// in the Synthi host runner / runtime boundary; this file gives core.cpp
// and host_runner.cpp a stable declaration set.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

use crate::hmr::compile_manifest::{DeviceVendor, GpuBuildBlock};

pub const SYNTHI_GPU_RUNTIME_HEADER: &str = "synthi_gpu_runtime.h";

pub fn render_gpu_runtime_header(gpu: &GpuBuildBlock) -> String {
    let vendor_define = match gpu.vendor {
        DeviceVendor::Cuda => "#define SYNTHI_GPU_VENDOR_CUDA 1\n#define SYNTHI_GPU_VENDOR_ROCM 0",
        DeviceVendor::Rocm => "#define SYNTHI_GPU_VENDOR_CUDA 0\n#define SYNTHI_GPU_VENDOR_ROCM 1",
    };
    let vendor_string = gpu.vendor.as_str();

    format!(
        r#"#pragma once
#ifndef SYNTHI_GPU_RUNTIME_H
#define SYNTHI_GPU_RUNTIME_H
// Generated by Synthi. Do not edit by hand.
// Runtime contract for GPU HMR sidecar modules.

#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <type_traits>

{vendor_define}
#define SYNTHI_GPU_VENDOR "{vendor_string}"

#ifndef SYNTHI_GPU_VECTOR_TYPES_READY
#define SYNTHI_GPU_VECTOR_TYPES_READY 1
#if defined(__has_include)
#  if SYNTHI_GPU_VENDOR_ROCM && __has_include(<hip/hip_vector_types.h>)
#    include <hip/hip_vector_types.h>
#    define SYNTHI_GPU_HAS_VENDOR_VECTOR_TYPES 1
#  elif SYNTHI_GPU_VENDOR_CUDA && __has_include(<vector_types.h>)
#    include <vector_types.h>
#    define SYNTHI_GPU_HAS_VENDOR_VECTOR_TYPES 1
#  endif
#endif
#ifndef SYNTHI_GPU_HAS_VENDOR_VECTOR_TYPES
#define SYNTHI_GPU_HAS_VENDOR_VECTOR_TYPES 0
#endif
#if !SYNTHI_GPU_HAS_VENDOR_VECTOR_TYPES
struct int2 {{ int x; int y; }};
struct int3 {{ int x; int y; int z; }};
struct int4 {{ int x; int y; int z; int w; }};
struct uint2 {{ unsigned int x; unsigned int y; }};
struct uint3 {{ unsigned int x; unsigned int y; unsigned int z; }};
struct uint4 {{ unsigned int x; unsigned int y; unsigned int z; unsigned int w; }};
struct float2 {{ float x; float y; }};
struct float3 {{ float x; float y; float z; }};
struct float4 {{ float x; float y; float z; float w; }};
inline constexpr int2 make_int2(int x, int y) {{ return int2{{x, y}}; }}
inline constexpr int3 make_int3(int x, int y, int z) {{ return int3{{x, y, z}}; }}
inline constexpr int4 make_int4(int x, int y, int z, int w) {{ return int4{{x, y, z, w}}; }}
inline constexpr uint2 make_uint2(unsigned int x, unsigned int y) {{ return uint2{{x, y}}; }}
inline constexpr uint3 make_uint3(unsigned int x, unsigned int y, unsigned int z) {{ return uint3{{x, y, z}}; }}
inline constexpr uint4 make_uint4(unsigned int x, unsigned int y, unsigned int z, unsigned int w) {{ return uint4{{x, y, z, w}}; }}
inline constexpr float2 make_float2(float x, float y) {{ return float2{{x, y}}; }}
inline constexpr float3 make_float3(float x, float y, float z) {{ return float3{{x, y, z}}; }}
inline constexpr float4 make_float4(float x, float y, float z, float w) {{ return float4{{x, y, z, w}}; }}
#endif
struct Dim3 {{
    unsigned int x;
    unsigned int y;
    unsigned int z;
    constexpr Dim3(unsigned int x_ = 1, unsigned int y_ = 1, unsigned int z_ = 1)
        : x(x_), y(y_), z(z_) {{}}
}};
#endif

enum SynthiGpuLaunchArgKind : std::uint32_t {{
    SYNTHI_GPU_ARG_KIND_UNKNOWN = 0,
    SYNTHI_GPU_ARG_KIND_POINTER = 1,
    SYNTHI_GPU_ARG_KIND_INTEGER = 2,
    SYNTHI_GPU_ARG_KIND_FLOATING = 3,
    SYNTHI_GPU_ARG_KIND_ENUM = 4,
    SYNTHI_GPU_ARG_KIND_AGGREGATE = 5,
}};

template <typename T>
struct SynthiGpuLaunchArgKindFor {{
    typedef typename std::remove_cv<T>::type BareT;
    static constexpr std::uint32_t value =
        std::is_pointer<BareT>::value ? SYNTHI_GPU_ARG_KIND_POINTER :
        std::is_integral<BareT>::value ? SYNTHI_GPU_ARG_KIND_INTEGER :
        std::is_floating_point<BareT>::value ? SYNTHI_GPU_ARG_KIND_FLOATING :
        std::is_enum<BareT>::value ? SYNTHI_GPU_ARG_KIND_ENUM :
        SYNTHI_GPU_ARG_KIND_AGGREGATE;
}};

struct SynthiGpuLaunchArg {{
    const void* value_ptr;
    std::size_t value_size;
    std::uint32_t value_kind;

    constexpr SynthiGpuLaunchArg()
        : value_ptr(nullptr), value_size(0), value_kind(SYNTHI_GPU_ARG_KIND_UNKNOWN) {{}}
    constexpr SynthiGpuLaunchArg(const void* ptr)
        : value_ptr(ptr), value_size(0), value_kind(SYNTHI_GPU_ARG_KIND_UNKNOWN) {{}}
    constexpr SynthiGpuLaunchArg(void* ptr)
        : value_ptr(ptr), value_size(0), value_kind(SYNTHI_GPU_ARG_KIND_UNKNOWN) {{}}

    template <typename T>
    constexpr SynthiGpuLaunchArg(T* ptr)
        : value_ptr(static_cast<const void*>(ptr)),
          value_size(sizeof(T)),
          value_kind(SynthiGpuLaunchArgKindFor<T>::value) {{}}

    template <typename T>
    constexpr SynthiGpuLaunchArg(const T* ptr)
        : value_ptr(static_cast<const void*>(ptr)),
          value_size(sizeof(T)),
          value_kind(SynthiGpuLaunchArgKindFor<T>::value) {{}}

    constexpr SynthiGpuLaunchArg(std::nullptr_t)
        : value_ptr(nullptr), value_size(0), value_kind(SYNTHI_GPU_ARG_KIND_UNKNOWN) {{}}
}};

extern "C" {{

struct DeviceDescriptor {{
    const char* vendor;
    const char* const* arches;
    const char* const* kernels;
    int num_arches;
    int num_kernels;
    int constant_layout_bytes;
}};

struct SynthiGpuRuntime;

const DeviceDescriptor* device_descriptor();
void device_on_load(const unsigned char* prev_blob, std::size_t len);
std::size_t device_save_size();
void device_save_write(unsigned char* out, std::size_t cap);
unsigned long long device_kernel_sig_hash(const char* name);

bool synthi_gpu_launch_raw(
    SynthiGpuRuntime* gpu,
    const char* kernel_name,
    const void* grid,
    std::size_t grid_size,
    const void* block,
    std::size_t block_size,
    std::size_t shared_bytes,
    std::uintptr_t stream_token,
    const void* const* args,
    std::size_t arg_count);

std::uint64_t synthi_gpu_launch_generation();

bool synthi_gpu_launch_raw_checked(
    SynthiGpuRuntime* gpu,
    const char* kernel_name,
    const void* grid,
    std::size_t grid_size,
    const void* block,
    std::size_t block_size,
    std::size_t shared_bytes,
    std::uintptr_t stream_token,
    const void* const* args,
    std::size_t arg_count,
    std::uint64_t expected_generation);

bool synthi_gpu_launch_raw_arg_info_checked(
    SynthiGpuRuntime* gpu,
    const char* kernel_name,
    const void* grid,
    std::size_t grid_size,
    const void* block,
    std::size_t block_size,
    std::size_t shared_bytes,
    std::uintptr_t stream_token,
    const SynthiGpuLaunchArg* args,
    std::size_t arg_count,
    std::uint64_t expected_generation);

bool synthi_gpu_launch_raw_arg_info(
    SynthiGpuRuntime* gpu,
    const char* kernel_name,
    const void* grid,
    std::size_t grid_size,
    const void* block,
    std::size_t block_size,
    std::size_t shared_bytes,
    std::uintptr_t stream_token,
    const SynthiGpuLaunchArg* args,
    std::size_t arg_count);

void synthi_gpu_register_buffer(
    SynthiGpuRuntime* gpu,
    void* ptr,
    std::size_t bytes,
    const char* semantic_name,
    const char* lifetime_hint);

void synthi_gpu_record_host_identity(
    const char* role,
    const void* identity_ptr,
    std::uint64_t aux_identity);

void synthi_gpu_record_output_oracle(
    const char* oracle_id,
    const char* kind,
    const char* expected_value,
    const char* actual_value,
    bool passed);

void synthi_gpu_record_original_host_path(
    const char* host_path_id,
    const char* dispatch_table_entry_id,
    bool dispatch_boundary_observed);

bool synthi_gpu_pack_buffer(const char* semantic_name, const void* ptr, std::size_t bytes);
bool synthi_gpu_restore_buffer(const unsigned char* blob, const char* semantic_name, void** out_ptr);

}} // extern "C"

struct SynthiGpuLaunchTable {{
    std::uint64_t generation;
    bool (*launch_raw)(
        SynthiGpuRuntime*,
        const char*,
        const void*,
        std::size_t,
        const void*,
        std::size_t,
        std::size_t,
        std::uintptr_t,
        const SynthiGpuLaunchArg*,
        std::size_t,
        std::uint64_t);
}};

inline SynthiGpuLaunchTable synthi_gpu_launch_table() {{
    return SynthiGpuLaunchTable{{
        synthi_gpu_launch_generation(),
        &synthi_gpu_launch_raw_arg_info_checked,
    }};
}}

inline std::uintptr_t synthi_gpu_stream_token(std::nullptr_t) {{
    return 0;
}}

template <typename Stream>
inline std::uintptr_t synthi_gpu_stream_token_impl(Stream stream, std::true_type) {{
    return reinterpret_cast<std::uintptr_t>(stream);
}}

template <typename Stream>
inline std::uintptr_t synthi_gpu_stream_token_impl(Stream stream, std::false_type) {{
    return static_cast<std::uintptr_t>(stream);
}}

template <typename Stream>
inline std::uintptr_t synthi_gpu_stream_token(Stream stream) {{
    return synthi_gpu_stream_token_impl(stream, typename std::is_pointer<Stream>::type());
}}

template <typename Grid, typename Block, typename Stream>
inline bool synthi_gpu_launch(
    SynthiGpuRuntime* gpu,
    const char* kernel_name,
    const Grid& grid,
    const Block& block,
    std::size_t shared_bytes,
    Stream stream,
    std::initializer_list<SynthiGpuLaunchArg> args) {{
    const SynthiGpuLaunchTable table = synthi_gpu_launch_table();
    return table.launch_raw(
        gpu,
        kernel_name,
        static_cast<const void*>(&grid),
        sizeof(Grid),
        static_cast<const void*>(&block),
        sizeof(Block),
        shared_bytes,
        synthi_gpu_stream_token(stream),
        args.begin(),
        args.size(),
        table.generation);
}}

inline void synthi_register(
    SynthiGpuRuntime* gpu,
    void* ptr,
    std::size_t bytes,
    const char* semantic_name,
    const char* lifetime_hint) {{
    synthi_gpu_register_buffer(gpu, ptr, bytes, semantic_name, lifetime_hint);
}}

inline void synthi_register(void* ptr, std::size_t bytes, const char* lifetime_hint) {{
    synthi_gpu_register_buffer(nullptr, ptr, bytes, nullptr, lifetime_hint);
}}

inline void synthi_host_identity(
    const char* role,
    const void* identity_ptr,
    std::uint64_t aux_identity = 0) {{
    synthi_gpu_record_host_identity(role, identity_ptr, aux_identity);
}}

inline void synthi_output_oracle(
    const char* oracle_id,
    const char* kind,
    const char* expected_value,
    const char* actual_value,
    bool passed) {{
    synthi_gpu_record_output_oracle(oracle_id, kind, expected_value, actual_value, passed);
}}

inline void synthi_original_host_path(
    const char* host_path_id,
    const char* dispatch_table_entry_id,
    bool dispatch_boundary_observed = true) {{
    synthi_gpu_record_original_host_path(
        host_path_id,
        dispatch_table_entry_id,
        dispatch_boundary_observed);
}}

#endif // SYNTHI_GPU_RUNTIME_H
"#
    )
}

pub async fn ensure_gpu_runtime_contract_header(
    workspace_dir: &Path,
    gpu: &GpuBuildBlock,
) -> Result<PathBuf> {
    let body = render_gpu_runtime_header(gpu);
    let path = workspace_dir.join(SYNTHI_GPU_RUNTIME_HEADER);
    tokio::fs::write(&path, &body)
        .await
        .with_context(|| format!("writing {}", path.display()))?;
    let internal_path = workspace_dir
        .join(".synthi")
        .join("generated")
        .join("gpu")
        .join(SYNTHI_GPU_RUNTIME_HEADER);
    if let Some(parent) = internal_path.parent() {
        tokio::fs::create_dir_all(parent)
            .await
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    tokio::fs::write(&internal_path, &body)
        .await
        .with_context(|| format!("writing {}", internal_path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hmr::compile_manifest::{
        DeviceCompiler, FatbinStrategy, GpuBuildBlock, SnapshotMode,
    };
    use std::fs;
    use std::process::Command;

    fn gpu(vendor: DeviceVendor) -> GpuBuildBlock {
        GpuBuildBlock {
            vendor,
            device_compiler: match vendor {
                DeviceVendor::Cuda => DeviceCompiler::Nvcc,
                DeviceVendor::Rocm => DeviceCompiler::Hipcc,
            },
            arch: vec!["sm_80".to_string()],
            device_flags: vec![],
            runtime_libs: vec![],
            snapshot_mode: SnapshotMode::Auto,
            fatbin_strategy: FatbinStrategy::SidecarModule,
            device_roles: Vec::new(),
            device_link: Default::default(),
        }
    }

    #[test]
    fn header_declares_launch_and_lifecycle_contract() {
        let h = render_gpu_runtime_header(&gpu(DeviceVendor::Cuda));
        assert!(h.contains("synthi_gpu_launch_raw"));
        assert!(h.contains("synthi_gpu_launch_raw_checked"));
        assert!(h.contains("synthi_gpu_launch_raw_arg_info_checked"));
        assert!(h.contains("struct SynthiGpuLaunchArg"));
        assert!(h.contains("value_kind"));
        assert!(h.contains("SYNTHI_GPU_ARG_KIND_POINTER"));
        assert!(h.contains("SynthiGpuLaunchTable"));
        assert!(h.contains("inline bool synthi_gpu_launch"));
        assert!(h.contains("synthi_gpu_stream_token(std::nullptr_t)"));
        assert!(h.contains("const DeviceDescriptor* device_descriptor()"));
        assert!(h.contains("void device_on_load"));
        assert!(h.contains("std::size_t device_save_size()"));
        assert!(h.contains("void device_save_write"));
        assert!(h.contains("unsigned long long device_kernel_sig_hash"));
        assert!(h.contains("synthi_gpu_record_host_identity"));
        assert!(h.contains("inline void synthi_host_identity"));
        assert!(h.contains("synthi_gpu_record_output_oracle"));
        assert!(h.contains("inline void synthi_output_oracle"));
        assert!(h.contains("synthi_gpu_record_original_host_path"));
        assert!(h.contains("inline void synthi_original_host_path"));
    }

    #[test]
    fn header_is_vendor_specific_without_cuda_or_hip_headers() {
        let cuda = render_gpu_runtime_header(&gpu(DeviceVendor::Cuda));
        let rocm = render_gpu_runtime_header(&gpu(DeviceVendor::Rocm));
        assert!(cuda.contains("#ifndef SYNTHI_GPU_RUNTIME_H"));
        assert!(cuda.contains("#define SYNTHI_GPU_RUNTIME_H"));
        assert!(cuda.contains("#define SYNTHI_GPU_VENDOR_CUDA 1"));
        assert!(rocm.contains("#define SYNTHI_GPU_VENDOR_ROCM 1"));
        assert!(!cuda.contains("cuda_runtime.h"));
        assert!(!rocm.contains("hip/hip_runtime.h"));
        assert!(rocm.contains("#    include <hip/hip_vector_types.h>"));
        assert!(cuda.contains("#    include <vector_types.h>"));
        assert!(rocm.contains("struct Dim3"));
        assert!(rocm.contains("struct float3"));
    }

    #[test]
    fn generated_header_accepts_common_stream_token_shapes() {
        let dir = tempfile::tempdir().unwrap();
        let header_path = dir.path().join(SYNTHI_GPU_RUNTIME_HEADER);
        let smoke_path = dir.path().join("stream_token_smoke.cpp");
        fs::write(
            &header_path,
            render_gpu_runtime_header(&gpu(DeviceVendor::Cuda)),
        )
        .unwrap();
        fs::write(
            &smoke_path,
            r#"#include "synthi_gpu_runtime.h"

void smoke(SynthiGpuRuntime* gpu) {
    Dim3 grid{1, 1, 1};
    Dim3 block{32, 1, 1};
    float3 point{0.0f, 1.0f, 2.0f};
    int2 resolution{800, 600};
    int value = 0;
    const void* arg = &value;
    (void)point;
    (void)resolution;
    (void)synthi_gpu_stream_token(nullptr);
    (void)synthi_gpu_stream_token(static_cast<void*>(nullptr));
    (void)synthi_gpu_stream_token(0);
    (void)synthi_gpu_launch(gpu, "noop", grid, block, 0, nullptr, {arg});
    synthi_host_identity("smoke", gpu, 0);
    synthi_output_oracle("smoke", "sentinel", "1", "1", true);
    synthi_original_host_path("host-loop", "entry-noop", true);
}
"#,
        )
        .unwrap();

        let compiler = std::env::var("CXX").unwrap_or_else(|_| "c++".to_string());
        let output = Command::new(&compiler)
            .arg("-std=c++11")
            .arg("-fsyntax-only")
            .arg("-I")
            .arg(dir.path())
            .arg(&smoke_path)
            .output()
            .unwrap_or_else(|err| panic!("failed to run {compiler}: {err}"));

        assert!(
            output.status.success(),
            "generated GPU runtime header failed C++11 syntax check\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn generated_header_accepts_root_and_internal_includes() {
        let dir = tempfile::tempdir().unwrap();
        let root_header_path = dir.path().join(SYNTHI_GPU_RUNTIME_HEADER);
        let internal_dir = dir.path().join(".synthi").join("generated").join("gpu");
        let internal_header_path = internal_dir.join(SYNTHI_GPU_RUNTIME_HEADER);
        let smoke_path = dir.path().join("duplicate_include_smoke.cpp");
        let header = render_gpu_runtime_header(&gpu(DeviceVendor::Rocm));
        fs::write(&root_header_path, &header).unwrap();
        fs::create_dir_all(&internal_dir).unwrap();
        fs::write(&internal_header_path, &header).unwrap();
        fs::write(
            &smoke_path,
            r#"#include "synthi_gpu_runtime.h"
#include ".synthi/generated/gpu/synthi_gpu_runtime.h"

const DeviceDescriptor* smoke_descriptor();
"#,
        )
        .unwrap();

        let compiler = std::env::var("CXX").unwrap_or_else(|_| "c++".to_string());
        let output = Command::new(&compiler)
            .arg("-std=c++17")
            .arg("-fsyntax-only")
            .arg("-I")
            .arg(dir.path())
            .arg(&smoke_path)
            .output()
            .unwrap_or_else(|err| panic!("failed to run {compiler}: {err}"));

        assert!(
            output.status.success(),
            "duplicate GPU runtime header include failed C++ syntax check\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
