"""
Compiler Provider - Layer B Semantic Analysis

This provider runs actual compiler/interpreter dry-runs to detect
deep semantic errors that syntax analysis might miss.

Features:
- Actual compilation with dry-run flags
- Cross-file error detection
- Linker error mapping
"""

from __future__ import annotations

import asyncio
import logging
import os
import tempfile
import shutil
from typing import Any, Dict, List, Optional

from .providers import (
    DiagnosticProvider,
    DiagnosticSource,
    UnifiedDiagnostic,
    DiagnosticSeverity,
    CodeAction,
)
from .compiler_parsers import (
    parse_compiler_output,
    get_parser_for_language,
)


logger = logging.getLogger('intelligence.compiler_provider')


class CompilerProvider(DiagnosticProvider):
    """
    Provider for deep semantic analysis via actual compilation.
    
    This provider:
    - Runs compiler/interpreter in check mode
    - Parses stderr for errors
    - Maps errors back to source locations
    """
    
    # Compiler commands per language
    COMPILER_COMMANDS = {
        'cpp': {
            'check': ['g++', '-fsyntax-only', '-Wall', '-Wextra'],
            'compile': ['g++', '-c', '-o', '/dev/null'],
        },
        'c': {
            'check': ['gcc', '-fsyntax-only', '-Wall', '-Wextra'],
            'compile': ['gcc', '-c', '-o', '/dev/null'],
        },
        'typescript': {
            'check': ['tsc', '--noEmit'],
        },
        'python': {
            'check': ['python', '-m', 'py_compile'],
            'lint': ['python', '-m', 'mypy', '--no-error-summary'],
        },
        'rust': {
            'check': ['cargo', 'check', '--message-format=short'],
        },
        'go': {
            'check': ['go', 'build', '-o', '/dev/null'],
        },
    }
    
    def __init__(self, workspace_root: Optional[str] = None):
        self._workspace_root = workspace_root
        self._timeout = 10.0  # seconds
    
    @property
    def source(self) -> DiagnosticSource:
        return DiagnosticSource.COMPILER
    
    @property
    def priority(self) -> int:
        return 1  # Higher priority than LSP, lower than AI
    
    async def analyze(
        self,
        file_path: str,
        content: str,
        language: str,
        related_files: Optional[Dict[str, str]] = None,
    ) -> List[UnifiedDiagnostic]:
        """
        Run compiler check on the file.
        """
        lang_key = language.lower()
        
        # Get compiler command
        commands = self.COMPILER_COMMANDS.get(lang_key)
        if not commands:
            logger.debug(f"No compiler configured for language: {language}")
            return []
        
        # Create temp directory for compilation
        temp_dir = None
        try:
            temp_dir = tempfile.mkdtemp(prefix='synthi_compile_')
            
            # Write main file
            temp_file = os.path.join(temp_dir, os.path.basename(file_path))
            with open(temp_file, 'w', encoding='utf-8') as f:
                f.write(content)
            
            # Write related files
            if related_files:
                for rel_path, rel_content in related_files.items():
                    rel_temp = os.path.join(temp_dir, os.path.basename(rel_path))
                    with open(rel_temp, 'w', encoding='utf-8') as f:
                        f.write(rel_content)
            
            # Run compiler check
            output = await self._run_compiler(
                commands.get('check', commands.get('lint', [])),
                temp_file,
                temp_dir,
                lang_key,
            )
            
            if not output:
                return []
            
            # Parse output
            diagnostics = parse_compiler_output(output, language, temp_dir)
            
            # Remap temp paths back to original paths
            for diag in diagnostics:
                if temp_dir in diag.file_path:
                    diag.file_path = file_path
            
            return diagnostics
            
        except Exception as e:
            logger.error(f"Compiler analysis failed: {e}")
            return []
        finally:
            # Cleanup temp directory
            if temp_dir and os.path.exists(temp_dir):
                try:
                    shutil.rmtree(temp_dir)
                except Exception:
                    pass
    
    async def get_code_actions(
        self,
        file_path: str,
        content: str,
        diagnostics: List[UnifiedDiagnostic],
    ) -> List[CodeAction]:
        """
        Compiler doesn't directly provide code actions.
        These are generated by the AI provider.
        """
        return []
    
    async def _run_compiler(
        self,
        command: List[str],
        file_path: str,
        working_dir: str,
        language: str,
    ) -> str:
        """Run compiler command and return stderr."""
        if not command:
            return ""
        
        # Build full command
        if language in ['cpp', 'c']:
            # Add include paths for related files
            full_cmd = command + ['-I', working_dir, file_path]
        elif language == 'python':
            full_cmd = command + [file_path]
        elif language == 'typescript':
            full_cmd = command + [file_path]
        else:
            full_cmd = command + [file_path]
        
        try:
            process = await asyncio.create_subprocess_exec(
                *full_cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=working_dir,
            )
            
            stdout, stderr = await asyncio.wait_for(
                process.communicate(),
                timeout=self._timeout,
            )
            
            # Combine stdout and stderr (some compilers use stdout)
            output = stderr.decode('utf-8', errors='replace')
            if stdout:
                output += '\n' + stdout.decode('utf-8', errors='replace')
            
            return output
            
        except asyncio.TimeoutError:
            logger.warning(f"Compiler timed out: {' '.join(full_cmd)}")
            return ""
        except FileNotFoundError:
            logger.debug(f"Compiler not found: {command[0]}")
            return ""
        except Exception as e:
            logger.error(f"Compiler execution error: {e}")
            return ""


# Singleton instance
_compiler_provider: Optional[CompilerProvider] = None


def get_compiler_provider(workspace_root: Optional[str] = None) -> CompilerProvider:
    """Get or create the global CompilerProvider instance."""
    global _compiler_provider
    
    if _compiler_provider is None or workspace_root:
        _compiler_provider = CompilerProvider(workspace_root)
    
    return _compiler_provider
